### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#1]
Not sure if you want each separate bug to be entered as a separate issue or whether we list all bugs under one issue?

[Playing around to see if I can edit an existing issue.  And it appears I can.  But can someone else edit my issue?]

Is this id'd as bug #1 and other comments get automatically numbered - testing still.

**Comment by goodgeyes** [comment]
Bug # 2 - test

**Comment by goodgeyes** [comment]
bug_3:  Keith, I see you already implemented a fix for hyperlinks within topics.  Oops - wait!  now not there.  It was there earlier this morning when I created a new topic, but not there now.

**Comment by goodgeyes** [comment]
bug_4: Decision creation process - Makes no sense that anyone can turn any proposal into a decision at any time.  I feel there needs to be more specific steps to get to an official decision being registered.  A very important step missing is turning the proposal text into decision text where wordsmithing is critically important.  I feel the team needs to consent to final decision text too by going thru an iterative process of discovering the best possible text.

**Comment by goodgeyes** [comment]
bug_5: process workflow timers missing - All steps need countdown timers to keep the workflow moving toward final decisions.

**Comment by goodgeyes** [comment]
bug_6: alert non-responders to time period deadlines - The process needs alerts to show users what they have not engaged in yet.  Both internal and possibly external (email) reminders.

**Comment by goodgeyes** [comment]
bug_7: async facilitation - The process needs an auto solution that allows a circle member to jump in anytime as a proposal to decision facilitator.  But at the same time a clear set of rules that includes timers and alerts for when a facilitator does not keep the workflow on track - based on timers expiring.

**Comment by goodgeyes** [comment]
bug_8: expired unresolved workflows presentation - The system needs a tool that shows all workflows that are in limbo and unresolved.  Helping spark action to get the workflow back on a resolution track.

**Comment by goodgeyes** [comment]
Sorry, I had no idea I closed this.  So I'm learning from Ian that we should be opening separate issues for each bug.  So a lot of my bug mentions are not necessarily bugs in code vs. limitations, problems from my vantage point or enhancement requests in the current solution.  Do we want to handle these differently than bugs?  So should we use labels to distinguish differences?  

I'm a bit confused at why we are now shifting into GitHub to handle bug requests when before we were doing it within Weaver using a topic.  Are we saying Weaver is not properly setup for this now?  Or just that GitHub is better as is.

**Comment by goodgeyes** [comment]
I've moved all these into separate issues.

**Comment by iangilman** [comment]
Excellent, moving them to separate issues is great. 

I believe we're moving to GitHub for keeping track of concrete actionable TODO items, since in our recent discussions we have decided that Weaver shouldn't focus on that area (since there are so many other apps that do it well). Weaver will be more focused around decision making rather than day to day task management.
