### ISSUE TITLE
Current decisions list is not adequate

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#10]
A lot of work needs to be done on improving the process to create better decisions lists.

1.  The proposal text simply being copied into the decisions text is a bad solution.  As I've mentioned before I think the overall workflow process needs to include a whole series of steps to wordsmith a best set of words that more clearly defines the decision.
2.  Tagging should be a requirement.
3.  We need to capture several important attributes about all that went into the decision - timestamps of milestones as it steps thru workflow steps, circles, members, engagement vs. default pass thru history, etc.
4.  We also need much better linking of decisions back thru every step and vice versa - each step linked back & forward to each next step in the workflow.  So from any reference anyone can easily experience the full story of how a decision was made or a proposal idea was terminated without decision.
5.  We need a better tool for perusing/querying the decisions list - very similar to how GitHub allows you to look at all issues.

**Comment by iangilman** [comment]
This issue should probably be broken into separate issues with clear action items.

**Comment by agilepro** [comment]
1. I agree that the proposal text (at least from the examples we have so far) does not make a good decision text.  That is why the person creating the decision can edit the text. No issue.
2. How would you require tagging?   Two tags or you cant save it?  Three?  What does it mean to say that tagging is a requirement?
3. The people who consented is captured.  The time that they did so is captured.  I am not sure what the rest of this list really means.
4. Decisions are linked back to proposals, which includes all the responses to the proposals.  Proposals are linked to earlier and later modified proposals.  What else do you want linked?
5. How would you make perusing decisions better?

**Comment by agilepro** [comment]
This is a larger design / interaction discussion, best held in the Weaver design topics or meetings.  Closing here.
