### ISSUE TITLE
Proxy error when posting description

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#101]
I was preparing the meeting for this evening, clicked on another tab. When I came back to the meeting, found this error message.  Note, a few minutes later when I was updating the description for the Weaver Training topic, i got the same message - but my edits were updated.

![image](https://cloud.githubusercontent.com/assets/10082365/18550405/b8984f76-7b21-11e6-920d-172c4b4c2854.png)

![image](https://cloud.githubusercontent.com/assets/10082365/18550388/9807defc-7b21-11e6-94df-12918022f91e.png)

John

**Comment by agilepro** [comment]
As far as I can tell, this really was a network error in accessing the server.  Nothing I can do about it.
