### ISSUE TITLE
errant URL

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#102]
Note: when I copy the URL for the August 29 meeting minutes to reference in the Sep 15 meeting, I get the August 17 minutes' URL

**Comment by agilepro** [comment]
The link for a meeting is:  

http://server/cog/v/fujitsu/teranet-project/meetingFull.htm?id=7776

The 4-digit ID on the end uniquely identified the meeting.  All of the links use this form, and if the ID did not identify the meeting, you would never be able to display the meeting.

If yo successfully copied and pasted the entire URL, including the unique ID, then there can be no possibility that this addresses a different meeting.   If you could point me to the actual example where it happened we might determine what happened, but it is just far more likely that there was user error involved.
