### ISSUE TITLE
Can we find a way to limit the amount of email?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#104]
I wonder if there is a way to filter the emails that Weaver generates. I get so many in my inbox about every little thing that happens. For example, maybe we should have an option to limit the emails to meeting notifications, assignment of meeting agenda items, assignment of action items, opening of new topics. For example, I don't have any need to see in my email that I closed an item.

![image](https://cloud.githubusercontent.com/assets/10082365/18565691/c23771be-7b5e-11e6-91a0-5730149bfe11.png)

**Comment by agilepro** [comment]
We all are wondering the same thing.  It is not difficult to provide choices to people to limit email, it is just a  certain amount of work that pretty much anyone could do.

**Comment by agilepro** [comment]
there is an option now to MUST email from new topics.  Also, you will only receive these email if you are subscribed to the thread.  You can unsubscribe at any time.  This is significan capability in this direction.  I am sure this will be an ongoing discussion as well.
