### ISSUE TITLE
Thread conflict error message when downloading large file.

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#105]
While Weaver was downloading big video file, I went off to do some emails. When I went back to Weaver, the video was still downloading and I had the following error message.

![image](https://cloud.githubusercontent.com/assets/10082365/18565883/8e760c7c-7b5f-11e6-98cc-45787afbcf85.png)

**Comment by agilepro** [comment]
I experienced the same problem.  The error is reporting a muti-thread problem.   Only one thread can run at a time on a workspace.  (that is how we guarantee consistency.)  Each request is expected to complete within a certain amount of time, and when multiple requests come in at the same time, they wait for a while, then gives this error.  My GUESS is that for some reason the lock is being held during a download.  That would explain it, but it will take more research.  This problem only seems to happen when downloading a large file, or a couple of large files.

**Comment by agilepro** [comment]
I cleaned up a lot of issues around threading and lock holding in the current version.  Particularly, large files have been tested with many people using the system simultaneously.
