### ISSUE TITLE
Adding URL is not appearing in recent update list

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#106]
In the Weaver Tutorial workspace, I added a link to a training video. After about 10 minutes, the listing of Recent Updates on the front page of the workspace does not show the update. Should it? If so, how long does the update normally take?

**Comment by agilepro** [comment]
I tested and document additions NEVER appear on there.  That is an easy bug to fix.

By the way:  Things within a workspace ALWAYS appear instantly.    A workspace is always self-consistent.  The only time you worry a propagation delay is when you are looking at workspace lists which are collected FROM a bunch of workspace .  If you have multiple workspaces int eh list, then might be a delay, but if you are looking at only one workspace it will always update instantly.

**Comment by agilepro** [comment]
The problem was only when you add a URL Link.  That was not producing a history item.   Now it is, and that will cause the update to appear in the recent updates list
