### ISSUE TITLE
Document name default values not always useful

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#107]
When I go to Add a Document and choose add URL, I paste the URL in the URL line. Then, when I click in the Name line, the immediately autofills with most of the content of the URL line. I have to delete that before entering the name information.

**Comment by agilepro** [comment]
It autofills the name with everything after the last slash.   When dealing with a URL like: 

http://server/archive/documents/Snowflake.pdf

it will autofill with 

Snowflake.pdf

This works fine with almost all sites that are making document available as file which have been named by humans.   However, some sites take a different stance, and makes a long and cryptic name.  That long cryptic name gets placed in the name slot, and have to be deleted.  

Here is an example from Google Docs EDIT mode:

https://docs.google.com/document/d/1oe4U5MmAA3muUnGmVvZmc4rGHxSR_lst83CyNuW_xbg/edit

and the thing place in the name slot is

edit

I did a quick random search on "business in quebec" and chose the first PDF file in the search results.  This was the URL

https://www.osler.com/osler/media/Osler/reports/doing-business-in-canada/Doing-Business-in-Quebec.pdf

and in this case, the default document name would be

Doing-Business-in-Quebec.pdf

That is quite convenient.  

The question we must grapple with is HOW OFTEN is each pattern used, and how often will this produce good results as opposed to annoying results.  Probably more research is needed.  However, the down-side is simply that you have to press 'ctrl-a' to select the entire name before you type.  Can we come up with an approach that more readily gets a suitable name?

**Comment by agilepro** [comment]
not update, so closing.
