### ISSUE TITLE
can't add member

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#110]
Tried to add a member to the Dynamic Community Governance workspace. Tried to add Monika Megyesi - who is already in the system. 

System would not allow me to add her.

**Comment by agilepro** [comment]
What happened that prevented this.  Did you type and her name didn't appear?  Did you add the name but get an error?  Did you click the button and it failed to respond?  

Also, after you add some to the list, you have to click save.   I mentioned this around the time the new UI for putting people in a list was added, but that might be easy to overlook.

-Keith

**Comment by agilepro** [comment]
I just added her.  i think the problem was with the TWO copies of Alison that you have in the list.  Fixed the problem with duplicate people, so I am assuming this is fixed now.
