### ISSUE TITLE
what time is it?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#111]
I cloned our meeting for Nov2 / 3 changed the time to EDT but there was no way for me to specify what timezone I mean it to be - actually im in India. Need to have timezone indicator

**Comment by agilepro** [comment]
Added a timezone indicator after the date/time value.  You can ONLY add time according to your current timezone.  The indicator tells you what timezone you are currently in and entering for.  To enter a time as if you are in a different time zone, just change the timezone setting of the computer you are using, and the entire base (after refresh) should appear in that time zone.
