### ISSUE TITLE
access to tutorials

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#114]
I would like to give Gopi access to the Weaver Tutorials workspace but I don't have Admin access and trying to copy the links over to his SSY workspace is awkward and there is no way for him to pass on the tutorials to others. Can we make this easier by creating general access to anyone who is a member of any workspace?

**Comment by agilepro** [comment]
That is the way it has always been: any member can invite others to be members.  Did you have a problem adding him as a member, or did you just assume you needed to be admin?
