### ISSUE TITLE
faked me out

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#115]
another admin comment. I tried to add Gopi Muvva as a member of the Weaver tutorial and the system seemed to accept him and put a symbol G in the member list. However, it didn't really access him (he's already uploaded his picture in his profile). So I had the impression that I'd added him but I really had not.

**Comment by agilepro** [comment]
I believe in the old system, you could enter the same email address with different capitalization and it would not notice they were the same email address.  This is fixed now, and duplicates are trimmed out.  IF this happens again, let me know.
