### ISSUE TITLE
missing cancer doctor

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#116]
Cancer doctors are listed as a role in Weaver Sandbox. However that role does not appear on the front page

**Comment by agilepro** [comment]
The Front Page only lists the roles that you are a player of.  It lists "your roles" -- the ones you play.

We should discuss whether this should list ALL roles.

**Comment by agilepro** [comment]
OK, (1) based on this comment and (2) since there are usually only a handful of total roles,  I changed the front page to display all roles, and to indicate which ones you are playing.
