### ISSUE TITLE
two user profiles ... whoops

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#117]
Just discovered that Gopi has two accounts. dont know how that happened - unless it happened when i tried to enroll him in Weaver Tutorials but didnt really have admin privileges. Dont know how to delete the incorrect account.

**Comment by agilepro** [comment]
New user management feature will allow you to replace all occurrences of one email address with another email address, effectively migrating whatever rights you can to one to the other.

The incorrect "account" will linger and cause no harm.
