### ISSUE TITLE
where's my comment

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#118]
I opened a proposal shaping section in a example topic in Weaver Sandbox. I pulled down the box that says edit your comment. I made a simple comment and saved but no comment appears. Also, the lines that say Picture Forming, Proposal Shaping, etc, just appear in the list. They do not section off the items in the topic or really serve any organizing function.

**Comment by agilepro** [comment]
Assume you are talking about THIS discussion:  https://interstagebpm.com/av/t/socio/weaver/noteZoom0004.htm

There are four history items at present time.  A proposal, a round, and two phase changes.  There all appear in chronological order: 11:28pm, 11:31pm, 11:43pm and 11:46pm  (pacific time) on Oct 24.  The organizing function is chronological.  If you had created rounds or proposals between 11:43 and 11:46 they would have fallen between these.

The only place that "Edit your Comment" appears is on an existing comment that you own.  There is a "Create Comment".  in both cases there is no "Save" button, just close (and if draft there is a post option).  I know it is really hard to remember exactly what happened after the fact.  Clearly there was an intent to create a comment and no comment appears in the list (there is proposal and round but no comment).  I am wondering if a comment was lost ... I have not been seeing any lost information recently, but that doesn't mean it is impossible.
