### ISSUE TITLE
operations meetings dreaming

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#119]
We haven't done much yet with operations meetings. Here are some design thoughts.
We should have a feature that would allow the person setting up the meeting to simple choose an item saying "List all action items" and the meeting would show all the action items listed by person (or by role). Everyone could then go into one place and update their items - as well as comment on others' items if applicable. Allow comments but take away minutes and proposals - they are not applicable to an ops meeting.

Also, it would be helpful to have the policy and ops meetings labelled in the meetings list.

**Comment by agilepro** [comment]
If you go to the action items list, you can choose the option "Status List View" which gives you all the action items as a big grid.  People can then you and easily change the status and due dates of the action items.

It does not sort by person, but you can type in a filter with the person's name and see all the items for a given person.

If is not "in" the meeting display, but it is one click away....

**Comment by agilepro** [comment]
We discussed the status view in the last meeting.  You said that meets your needs.  Leaving this here until we know that nothing else is needed.
