### ISSUE TITLE
Links to open new browser tabs

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#12]
There was one point on 22 Dec where I saw Keith had implemented a new solution for this.  By that afternoon it had disappeared and was back to the old way.  Still looking for the fix, so we are less apt to lose our typing.

**Comment by iangilman** [comment]
To be explicit: I believe the accepted proposal is to open offsite links (i.e. links to non-Weaver pages) in a new tab, but for links inside Weaver to replace the page as normal. This is pretty standard practice these days. You certainly don't want every click on a link to spawn a new tab or you'll soon have hundreds of them. 

That doesn't necessarily address your issue of losing text. One possible solution for that is for the app to save unsent text in the browser's local storage and bring it back when you hit the back button.

**Comment by agilepro** [comment]
Ever since the implementation of the new text editor (March or something like that) links have not been opening in new tabs.  I have found the reason for that, and expect it will be in the next server refresh.   This did not come and go since March.

**Comment by agilepro** [comment]
links to external resources now open in a different tab/window.
