### ISSUE TITLE
blanked out blank

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#120]
I went to create a new workspace. I opened the Sociocracy AccountCreateProject page and clicked Create New Workspace. I got an error message. Because there was no visible data entry field next to New Workspace Name, it was not clear to me that I needed to click next to that instruction to get a data entry field. The way it works now is "cute" but not clear. Please give me a UI that holds my hand.

**Comment by agilepro** [comment]
It is hard to see the boxes that you have to type into.   I have altered the display individually in a few places, but that seem to be error prone having to find and fix each input box in the product.  I have asked Sven if there is a global style that we can change that would make it consistent everywhere.  It would be best to have a single style that works everywhere.

**Comment by agilepro** [comment]
I have reverted the input boxes to be "bootstrap" standard which I think is much more useful.  They now appear as boxes, and they glow blue when the focus is in them.
