### ISSUE TITLE
mass entry missing

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#121]
I want to add about 20 names to the new worksite: Pune Post-Workshop Meet Up Site. However, the wizard only lets me submit one name at a time. I can't just drop in a list of emails.

**Comment by agilepro** [comment]
The question is: how often will you do this.  Copying and pasting 20 email addresses individually takes about 20 seconds, certainly no more than a minute.   Lets say that we imagine a 1000 users being added this way, that is 20 people adding 50 people each.  The time "savings" of such a feature would be no more than an hour, split across 20 people, or about 3 minutes each.

Creating the dialog to do this would take several hours of coding and several hours of testing.  I just can't see where the saving will be larger than the effort to save it.  It would be like paying $50 to get a coupon to save $10 somewhere else.  That is the reason that I have focused on other features that really make a difference in usability.
