### ISSUE TITLE
delete workspace

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#124]
By accident I created two workspaces for Pune. I can I delete one of them? I can't find the option.

**Comment by agilepro** [comment]
In "Workspace Admin" you will see "Workspace Mode"  of "Frozen" or "Deleted".   When you set it to Deleted, it mostly disappears.  Think of it as being in the recycle bin.  Later there is a sitewide function that actually finally removes it from disk.

**Comment by agilepro** [comment]
This is working.  Added the deleted workspace to appear on the Site Workspace list so that a site owner can find the deleted workspaces, and -- if desired -- bring them back.
