### ISSUE TITLE
where is Aim

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#125]
I remember Keith saying once that it is possible somewhere to put list the aim of a workspace. However, I can't find it. It's an important feature. Would like it to be easy to find. thanks.

**Comment by agilepro** [comment]
We have not talked about this much.  When you click on the Workspace Admin navigation item, the middle of the admin screen is a block called "Public Purpose"  That might not be the best name, but the idea is that this is the goal of the project, and I put "public" there to remind people that it will be seen by people who are not members of the project.   Try putting something in there, and see where it appears.
