### ISSUE TITLE
bug in invite system

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#129]
This problem is probably related to the previous issue. I registered Jeanette O'Conor on both the Weaver Tutorials workspace and the new Goa workspace and sent an invitation. However, she says never got the invite email:  "Ok I searched all emails and don’t see an invite. I tried to register at the site and it never sent me an email link either- so not sure what the bugs are."

I added her to the Goa workspace as an admin and also as a member. 

I then removed her name in both roles and registered and reinvited her. Several hours later she sent me this email: "Just an fyi I never got the fujitsu/weaver email invite you requested to be resent."

**Comment by agilepro** [comment]
I believe that the problem is that it is going into Jeanette's spam folder on her end of the transmission.
