### ISSUE TITLE
Current create a new decision process is inadequate

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#13]
Makes no sense that anyone can turn any proposal into a decision at any time. There should be specific steps baked into the standard workflow to get to an official decision being registered in the database. A very important step missing now is turning the consented proposal text into decision text where wordsmithing is critically important. The full team should consent to final decision text too by going thru an iterative process of discovering the best possible decision text.  Not everyone is great at wordsmithing, so especially important to get them help from others.

**Comment by iangilman** [comment]
I think the action item here is basically to implement @rgilman's "smart structured topics" proposal.

**Comment by agilepro** [comment]
This is a broader discussion and should be a Weaver discussion topic.

First: what is allowed today: only the original person that proposed the proposition can edit the proposition.  But anyone can make a "modified" proposition.  Anyone can turn a proposal into a decision.

Second: Should others be able to edit the proposal?  I have heard recently some comments that it is a shame that team members can not modify the proposal.  It is easy to make everone able to edit it, but what comes of that?  If I make a response, and then the proposal is changed, where does that leave my response?

Third: making the decision.  Almost all of the proposals I have seen are inappropriate for decision objects.  That means that some editing is required.  Who is allowed to do this?  Are there only certain people who can create decision objects?  Right now, anyone can.  There probably

**Comment by agilepro** [comment]
Closing due to this remaining vague and unclear for two months without remedy.
