### ISSUE TITLE
email weirdness

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#131]
The email challenge continues to be weird. I have tried several times to send an email from Weaver to invited Jeanette O'Conor to join the Goa and other worksites. I send the invite to joconor@mayactr.org. She is cc'd on this message and will receive this message at that address. I even went into Topics and sent an email from there. Still no luck.

Last night I sent an invite to Weaver Sandbox worksite to my wife, Ramona Buck (ramonabuck@gmail.com). She got the invite, no problem. So, I'm stuck as to how to troubleshoot this one. It appears that the problem is with Jeanette's email specifically.

**Comment by agilepro** [comment]
I believe this a problem with Jeanette receives the email, it is going into a spam folder somewhere.
