### ISSUE TITLE
disappearing comment

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#133]
I entered a comment on an agenda item for the meeting tomorrow (Dec 14). I subsequently decided to invoke a topic and thereby make the comments available - even if that mean renaming to topic. When I came back to the item, my original comment had disappeared.

**Comment by agilepro** [comment]
I will look int o making sure that all comments on agenda items are MOVED to the discussion topic, when you choose it.   But don't make any mistakes like choose the wrong topic, because once moved, it won't come back.
