### ISSUE TITLE
multiple invitations needed?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#135]
I just added someone to a new workspace for the Sociocracy Center Austria. I gave him both member and administrator roles in the workspace. 
Question: do I need to send an invitation for each role or is sending an invitation from the Member role enough to allow him to access both roles? I wasn't sure so I sent an invitation from both roles.

**Comment by agilepro** [comment]
No you do not need to send two invitations.

You can add and remove people from as many roles as you want to.  Adding and removing them has immediately effect.

You only need to send the invite if (1) you don't think they know about the role and want to inform them, or (2) you want to offer some help in registering a password with their email.  This is useful mainly with people who are new to the system.  Once they are signed up, you rarely need to send an invitation.  The "invitation" is to register their user account, and to join the Weaver system -- not really an invitation to the role per se.
