### ISSUE TITLE
Sync meetings have too many dead zones

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#14]
By dead zones I mean times when one or more persons are spinning their wheels about things like clarity of using tools or entering action items or proposals.  Others should not be made to suffer thru these time periods.  It's a real turn off.

I'm going to suggest that we focus on changing sync rules & tools to eliminate these dead zones.  One approach we could test immediately - in our next sync meeting - would be to all get into one Google doc.  Create a template for each agenda item and under each, put in placeholder names for each attending member.  This way we can each enter notes simultaneously.  We then can use comments to comment of others notes.  Then after the meeting individuals can use ALL the notes to generate action items and proposals.  

I would further suggest we start putting timers on some of these post sync meeting steps.  E.g. we could say everyone has 24 hours to finalize all their meeting notes.  Then another 24 hour period to finalize new action items, proposals, topics, etc. 

This way maybe we can avoid these dead zones in these sync meetings.  The added benefit is we get the simultaneous editing feature we all want.  It just is not in Weaver yet.  Note taking will much improve during the sync meeting.  Maybe we can also implement other useful 'move the meeting along faster' solutions like noting under your name under the 'up' agenda item - that you have nothing more you need to say verbally.  Maybe use a Red highlighted "I'm Good!" indicator note.

Other ideas along these lines?  Especially curious what John thinks - as it moves away from the traditional process and moves more into this realm I've been pushing for of having people participate in sync meetings but without speaking - instead using software tools to communicate and log feedback and input to what is happening in real time sync meetings.

Stick more closely to a set agenda schedule and this way you can pay attention on the stuff you are interested in and go do something else when those agenda items are on deck.  This even opens the door for a person being able to come to the doc before the meeting, add everything they want to say and don't attend the meeting at all.  Everyone else has the opportunity to see what you say for each agenda item.

Now when a sync meeting is started the facilitator can intro the meeting with something like:
We have 3 people live with us.  One has indicated he is happy not to be called on to speak (unless he raises his hand.)  Two have already checked in and provided notes of agenda items.  One person is on vacation.  But everyone now knows what to expect and the meeting can made run much more efficiently & effectively.

**Comment by iangilman** [comment]
This absolutely should be a Topic in Weaver, not an issue here in GitHub; issues should only be for actionable code issues, not free form discussions. That said, I think it's a great topic, and I look forward to discussing it over in Weaver!

**Comment by agilepro** [comment]
This is an involved discussion, so closing here.  We can discuss in the Weaver design topics and  meetings,
