### ISSUE TITLE
a different take on the action item status list

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#141]
Here is a chart that the group in India called Ahimsagram has developed for operations meetings. They are a kind of income sharing, living together community It blends in some holacracy practices in an interesting way. It is in a spreadsheet & so is hard to maintain over time. There are a couple of columns that contain information that doesn't appear in the action item status list. Would like to discuss so we can decide whether to use at least some of the elements from this layout. (It would be attractive to holacracy users.) https://docs.google.com/spreadsheets/d/1NuNONqcH0s8648XYFMoepX9Lz54cmz5UtZVfSkKoacU/edit?usp=sharing

**Comment by agilepro** [comment]
Please introduce Ahimsagram to our status list view.  I believe it handles everything he wants just about, and maybe more in other areas.

![image](https://user-images.githubusercontent.com/5544889/34427988-d74f0ee4-ebfc-11e7-9aec-6cb780ac9757.png)
