### ISSUE TITLE
The way time is displayed

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#146]
I just got a Weaver reminder for an international call involving people in India, Spain, and USA that said:

Scheduled time: Jan 26, 2017 04:00 PST

The internationals will not know what "PST" means. I suggest, therefore, that we also add the time in GMT. In this case it would say: "Scheduled time: Jan 26, 2017 04:00 PST (GMT-8)"

It would be really cool if the time could adapt to each person's location like this:

"Scheduled time: Jan 26, 2017 07:00 EST (GMT-5)"

**Comment by agilepro** [comment]
Made this change and checked in.  Should appear soon.
