### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#147]
In the Certification Mentoring workspace I created an agenda item about topics in advanced sociocracy training. when I tried to open it, I got a strange screen. (Was able to get out of screen by clicking Action Items

![image](https://cloud.githubusercontent.com/assets/10082365/22334608/67ac44dc-e3a9-11e6-8339-23a52e0c2e23.png)

**Comment by agilepro** [comment]
What appears to have happened at this time was that two people created a meeting almost simultaneously.  Once created and then the other created and wrote over the first.  This error is complaining that the meeting in question does not exist ... that is the meeting with the ID specified in the URL, and indeed it does not exist.   Did it ever exist?  My guess is that it was overwritten.  Leave this open to thinkg about how to prevent this problem .

**Comment by agilepro** [comment]
I am hoping this is fixed with the thread-safe coding this weekend.
