### ISSUE TITLE
a place for users to record comments & suggestions

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#148]
This message is from the Omnizent workspace:
"New topic: Log of New Users documenting their First Experiences with Weaver in workspace Omnizient
New Users are invited to share their First Experiences with Weaver."

Basically he is suggesting that we have a prominent item (maybe in the lefthand column) that says something like: User Feedback. That can point at a user friendly message template (that could go to GitHub?) where people can give their feedback.

**Comment by agilepro** [comment]
finally done.
