### ISSUE TITLE
Feedback on being a new user

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#149]
Amarendra (in the Omnizent workspace) purposely did not look at the training videos so that he could see how intuitive Weaver is without any instruction. Here is what he experienced: 
[https://docs.google.com/presentation/d/1Kt4GKJbVIoBtazkQ-gHs8xxBSIlgrY8oxw7zGFjCluE/edit?usp=sharing]

**Comment by agilepro** [comment]
Everything is addressed except the "Create Something" main level menu

**Comment by agilepro** [comment]
Create Something" main level menu is now available
