### ISSUE TITLE
problem report logging in

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#150]
message from a user:
Begin forwarded message:

From: Donna Foley <donnaf@va.childcareaware.org>
Subject: RE: New Topic: Minutes 1.28.2017
Date: January 31, 2017 at 3:54:04 PM EST
To: Savanna Love <vaeceadmin@vaece.org>

Savanna,
 
I have tried to access weaver and it takes me to a login page, is there already a password created for me.  I have tried registering but it will not allow me to. 
 
Best regards,
Donna
 
Donna Foley
Child Care Aware® of Virginia
Quality Assurance & Data Services Coordinator
302 Turner Rd., Suite D
Richmond, VA 23225
(540) 420-2474
donnaf@va.childcareaware.org
www.va.childcareaware.org
 
 
 
From: Savanna Love [mailto:vaeceadmin@vaece.org] 
Sent: Tuesday, January 31, 2017 10:34 AM
To: Donna Foley <donnaf@va.childcareaware.org>
Subject: New Topic: Minutes 1.28.2017
 
New topic: Minutes 1.28.2017 in workspace VaAYEC Board

**Comment by agilepro** [comment]
The browser is putting something there that looks like a password, but it is not actually there.  If you just type in the desired password like normal it should work.
