### ISSUE TITLE
need worksite administrators to have the power to create child circles

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#152]
See copy of messages:

Hi Keith, 
This email led to a discussion with Gregg which led to an insight. Is there anyway that we can let an administrator create child circles without being one of us "Weaver Executive Dudes"? Gregg is rolling with his organization but they have to come to me to set up their lower organizational structure.

Also sent this note to GitHub

John
---------- Forwarded message ----------
From: Gregg Kendrick, Basileia <gkendrick@basileia.org>
Date: Wed, Feb 1, 2017 at 8:35 PM
Subject: Fwd: Weaver request approved
To: John Buck <john.buck@sociocracyconsulting.com>
Cc: Jenn Slack <director@ourneighborhoodcdc.com>, Savanna Marie Love <savanna.m.love@gmail.com>, Holly McCartney PhD <hbmccartney@gmail.com>

Hi John,

Savanna will be the key technical contact for VAECE (changing their name to VaAYEC soon) and is the key Administrator on their Weaver system. Jenn Slack is the Lead for the SCM Implementation Circle. I have been providing consulting support as an SCM expert. So please include Savanna, Jenn and myself in any communications as this Weaver system gets set up for VAECE (VaAYEC).

Let me clarify the request:

Please add 5 sub-circles to the Leadership Circle which will be double-linked:
Chapter Support Circle
Conference Circle
Public Policy Circle
Communications and Member Recruitment Circle
Professional Development and Quality Circle
Additionally, there are two helping circles to the Board Circle
nvaeyc/vaaeyc Transition Circle 
SCM Implementation Circle
And one helping circle to the Leadership Circle
Conference Guidelines circle 

Please make Savanna the initial Administrator of all of the above circles, and she can add other administrators and members as needed.

Let us know if you have any questions regarding this request.

Thanks, John!

Gregg

**Comment by agilepro** [comment]
Gregg was set up with a site, and he can create workspaces.
