### ISSUE TITLE
End user comments

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#154]
Copy of email dated February 2 (refer to email of that date to Keith from John to get a clear format)

Hi Keith, 
I had a good call today with Savanna Love and Gregg Kendrick. They are going full bore using Weaver and have the following feedback. One result of the call is that I created a Feedback on Weaver workspace. I will also put this note into GitHub.

Savanna and Gregg, please feel free to comment on my comments if I have not got something reported accurately or left out something.

When you have a document listed in Documents and want to access it, you click on it and then have to Click on URL again to get the document. Would like to be able to do it in one click. (Maybe there could be an something in the Options box that would let you get more detail.)
Speaking of Options boxes, would be great to have them not be way off in the upper right corner and "Options" understates what they really are. Maybe they should be named "Controls".
The only big problem Savanna reported is problems with  initial sign-ons. I forwarded an email from her earlier this week. One problem may be the invite email expiring. Maybe the admin could have control optional control on how long the invite email aging is?
One of the experiments Savanna tried is to use a Decision box to ask people to consent to meeting minutes once it is loaded into topics - without having to wait until the next meeting. Some people have been responding but many others not. Savanna thinks that part of the problem is that Weaver generates so many emails that people ignore them. 
She would like to be able to control when people receive an email and when not. For example, she would not transmit an email for minor changes.  
We looked at the email control options and realized that we did not understand what the options mean, and what does it mean if you check more than one box - eg.  what does it mean if you click both Mute Email Notifications and Receive Digest? (I've not used those options so I wasn't sure either.) 
Regarding the front page.
they would like the vision, mission, aim of a workspace to appear on the home page and not just obscurely in the Admin Workspace. They would like to have the option of using a template to describe the workspace in terms of vision, mission, aim (core sociocracy concepts). 
Savanna says that when she goes to a workspace, she would like to be able to see all of her workspaces. Depending on which diagram she is working with, some of the circles are there and some not. I'm not sure if they sometimes disappear when she clicks on the Workspace on the menu.
They would like to be able to see more space around roles and circles so they can be clear about what info defines the circle and what defines the role - in a way that is present for people when they come on line. They pointed out that Glass Frog does a good job in this aspect.
Browser, etc.
Savanna says that Weaver does not work very well in her Safari browser & so she has to use her Chrome browser. 
They suggest that we get a domain name that says Weaver rather than interstagebpm - if for no other reason than to avoid confusion.
Documents
They are already building up a lot of documents in their system. If the documents lists are long, it's hard to find a particular document, even with labels. She misses being able to set up a folder/subfolder system like in google. We talked about the possibility of creating labels that are specifically subfolders of primary labels. 
We also talked about the need to be able to archive documents - maybe an archiving function. (Much easier to handle 200 documents than 1000 documents.
Thanks again Savanna and Gregg for this feedback!

John

**Comment by agilepro** [comment]
Actions taken:

* attached documents have a pull down to let you choose what you want to do directly
* options "way off" in upper right: others have commented on how important it is to have consistency and to find things in the same place.  Particularly, once they got used to options being there, they complained when it was NOT there.  They just need more experience.
* Sign on problem was with timeout
* email flood is not a problem any more
* workspace purpose is listed.  If you put vision and aim in there, then it will appear there.
* You can see all workspace you are in with:  Workspaces > Participant
* domain name settled
* You CAN use labels just like file folders just like Google, you just have to do it. (i.e. in google you have to create folders, in Weaver you have to create a label.)
