### ISSUE TITLE
security warning appears

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#159]
starting in the last day or two, whenever I go to a new Weaver screen, I get the following message:

![image](https://cloud.githubusercontent.com/assets/10082365/23597587/31a71612-025a-11e7-8d0c-2417c6fc656d.png)

**Comment by agilepro** [comment]
This error can mean a number of things.  It can mean that you are encountering a "man in the middle" attack.  That is, a server is intercepting your traffic and forwarding it on, and returning the values to you.  However, the man in the middle reads everything you send.  The certificate installed on that server allows you to make a secure connection, and it prevents man in the middle attacks, however, the way it does so is by presenting this error message. 

I just checked now, and the certificate on the server is fine and checks OK here.  

I checked with two browsers.

This seems to indicate that you have a network problem.....

**Comment by agilepro** [comment]
Click on "advanced" and make a security exception.

What is happening is that the round trip (your browser, to the server, and
back) is going though a server which is decrypting the traffic, and
inserting its own encryption.  This mean that your traffic to and from the
server is not secure.  The browser can detect this by checking the
encryption of the certificate and when it finds that what you are getting
does not exactly match what the server is sending, it knows that someone
along the chain is doing something bad.

Making an exception will be saying: "yes, i know there is something wrong
with the channel, but let me see the web site anyway."

I recommend that you NOT do this for your bank or any thing private.

-Keith

------------------------------------------------------
Keith D Swenson
408.859.1005
http://social-biz.org/

**Comment by agilepro** [comment]
This is a problem with the network between you and the server.  There is nothing we can fix in the product.
