### ISSUE TITLE
Hard to find comments on meeting pages

### ISSUE THREAD

**Issue by iangilman** [agilepro/cognoscenti#16]
Problem: I get an email notification about a new comment on a meeting page and I click on the link, and all I see is the meeting page with all of the agenda items collapsed. I have no idea which agenda item contains the new comment, so I have to dig through each one individually. 

Possible solutions: 

* for starters, the new comment link should take me directly to that comment, with the agenda expanded
* it might also be handy to have an "expand all" feature

**Comment by agilepro** [comment]
Yes, I agree. In the case where you follow a link, it really should take you all the way there.  Maybe *IF* there is a link to a comment, then expand all, and put you there.  Should be able to find a way to make this work.

**Comment by agilepro** [comment]
This is now fixed.
