### ISSUE TITLE
another hit

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#161]
I just ran across another error like with new workspace but different activity - adding a doc

![image](https://cloud.githubusercontent.com/assets/10082365/23748728/e00dc420-04ea-11e7-9daa-806886f4593f.png)

**Comment by johnabuck** [comment]
Follow on report: this problem appeared only once. Had no further trouble when I revisited the site and repeated the document download.

**Comment by agilepro** [comment]
this appears to be an extremely unlikely coincidence.  There is a 1 : 10,000 chance that two people will independently get the same internal ID for what they are working on.  Both have to act at the same time (within a few seconds) and then be unlucky.  That is all I can think at this time that happened.
