### ISSUE TITLE
cant add new workspace

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#163]
I am trying to add a new workspace but when I click on Sites I see only the following image:

![image](https://cloud.githubusercontent.com/assets/10082365/24074387/dcb62386-0bc4-11e7-8c45-91c7957d10c0.png)

I can only list sites, I can't click on Socio and then choose the option of adding a new workspace. It doesn't work to click on the partial box above "list sites"

**Comment by agilepro** [comment]
When you got to the "List Sites" page, the sites are listed, and you can click on one.  There you can create a workspace.   Also, if you go to any workspace, you can click on the site in the breadcrumbs, and go to the site that way.   I sent an email with images of both of these, but have not head back yet.
