### ISSUE TITLE
User interface request re roll call

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#168]
Today in the meeting of the Certification Mentoring workspace, we noted that two of the members we expected were missing. The meeting was set in Running mode. I looked for the Roll Call but couldn't find it. I switched the meeting back to Planning mode and found the Roll Call. 

Request that the Roll Call feature be visible in Running Mode as well as Planning Mode.

**Comment by agilepro** [comment]
There is an Options Menu item called "Show Roll Call" that does just that.
