### ISSUE TITLE
cant delete

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#169]
Cant delete misplaced document included in a topic. Specifically, I want to delete the April 13 document entry

![image](https://cloud.githubusercontent.com/assets/10082365/24990529/b45491de-1fe2-11e7-8e92-8ba4e4319b57.png)

**Comment by agilepro** [comment]
That document is on the "meeting entry" in the history.  You can not delete that as long as the meeting includes this topic as an agenda item.
