### ISSUE TITLE
date on Keith's example question in missing responses report is a future date - tomorrow - in my view of it

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#17]

**Comment by agilepro** [comment]
Yes, that is a due date.   It is due tomorrow.

**Comment by goodgeyes** [comment]
Keith, so in Weaver we have dates object are created, opened or closed, completed, etc.
We now have timers.
It would be great to distinguish the two types.
Is it really hard to create a dynamic countdown timer in the UI/UX?
If a user saw a timer actually counting down this would clearly distinguish the two types.
