### ISSUE TITLE
automatic notice but not ready to send

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#170]
I am setting up the meeting for tomorrow. I cloned the previous meeting but the notice period is less than contained in that meeting. I got the notice:
![image](https://cloud.githubusercontent.com/assets/10082365/25185544/9edb1d42-24eb-11e7-80ff-7f1c853639c6.png)

It appears that if I wish to clone the meeting, I must send out a notice immediately but I'm not done setting up the meeting. So, if I want to clone the meeting I must send out a notice before I have it completely set up.

**Comment by agilepro** [comment]
Unfortunately the think for setting the notice period was lost in some fo the re-styling work.

(1) I have added that back in so you can set the notification period when creating/cloning a meeting.
(2) meetings are now created in "Draft" mode.  No email goes out until they are placed in "Plan" mode.
