### ISSUE TITLE
not needed emails

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#171]
I have been setting up the next Weaver top circle meeting. I got emails for each item I generated. These are examples of not-needed emails. Is not clear how I can limit them in the current set of controls. (or can I?)

![image](https://cloud.githubusercontent.com/assets/10082365/25186354/e9f7661c-24ed-11e7-941c-324b9fd95889.png)

**Comment by agilepro** [comment]
I have just implemented the "suppress email" on the comment feature.  When writing a comment, proposal, round, or minutes, you can decide whether to have email sent or not.
