### ISSUE TITLE
remove someone

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#173]
It is not clear how to remove someone from a role. If I click on the member icon, Remove is not an option.

**Comment by agilepro** [comment]
IF you bring up the dialog box with all the peple listed by name, there is a little X by their name, and that deletes them.  I think that is pretty clear.  HOWEVER it would be very nice to have it in the main window as one of the pull down options.  That should be easy to arrange.

**Comment by agilepro** [comment]
Clicking on someone now gives you the option to remove them
