### ISSUE TITLE
peer links in circle diagram

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#175]
Talking today with Gehan of Galgael (Scotland), I realize there is a need right now to show peer relationships. Eg in her case they have a compound structure that joins two organizations, a forprofit and a nonprofit, but  keeps them legally separate - hence two boards that have a peer-to-peer relationship (& exchange links).

**Comment by agilepro** [comment]
Sounds like a premium feature will to do for a good donation
