### ISSUE TITLE
two thoughts will preparing meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#179]
Two thoughts  in planning today's meeting
1) what happened to all the Topics in the Old Weaver Meeting. We had a lot a one point. 
2) need a way to share documents easily in linked workspaces. I wanted to move the ExO planning document from Old Weaver to the current board worksite. Old Weaver is linked to the New Weaver Board workspace. But I had to go into Old Weaver, find the link, and re-enter the link into the New Weaver Board document system.

**Comment by agilepro** [comment]
now an ability to clone documents between workspaces
