### ISSUE TITLE
where is the reminder function?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#184]
When I set up the meeting for Tuesday, June 13, I wanted to check the reminder function - how far in advance to send a reminder. However, that feature has disappeared. How can I send an automated reminder?

**Comment by agilepro** [comment]
right here:
![image](https://user-images.githubusercontent.com/5544889/34425158-5c16b1b4-ebde-11e7-871e-6d2e642dcd02.png)
