### ISSUE TITLE
Comment 2 about workspace personal settings.

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#187]
Regarding Template: 
_This workspace is not one of your template 

You can use this workspace as template for your future reference. If you mark this workspace as template then it will appear in the "List of Templates" in your profile's workspace page. At any time you can even stop using this workspace as template._ 

1) I don't know what it means to "use this workspace as template for your future reference." Is this option just for people listed as Administrators? Does it copy over members names to new workspaces? "future reference" for what?

2) What is a "profile" in the phrase "your profile's workspace page? Do you mean what I see when I click on Personal in the magenta column? But that page doesn't say anything about templates.

**Comment by agilepro** [comment]
Improved the message as follows:

![image](https://user-images.githubusercontent.com/5544889/34425325-ac2d379e-ebdf-11e7-939b-7a22d069d678.png)
