### ISSUE TITLE
Comment 3 about personal workspace settings

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#188]
**Digest**
_You are not receiving the digest for this workspace 

If you request to receive the digest of changes, then a summary of the changes to this workspace will be included in the period email (daily, weekly, or monthly) that you receive._ 

1) Where can I go to set the period for my periodic email?

2) If I click Receive Digest box, does it mean I will never receive individual emails?

**Comment by agilepro** [comment]
1. I added a sentence to clarify whhere you set the period.

2. No
