### ISSUE TITLE
Comment 4 - Personal Workspace Settings

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#189]
**Mute Email**

_You will receive email notification when new Topics are created 

Normally all members will receive an email when a new topic is created. This option allows you to disable that so that you will not receive any email when a new discussion topic is created._ 

1) Would it be accurate and clearer to say:
"Normally, you will receive an email whenever a new discussion Topic is created. You will also receive an email whenever there is a comment posted to a Topic. Click this box if you do not want to receive any emails at all about Topics."?

2) What about emails that are generated by setting up a new meeting? The draft meeting feature has suppressed some of the unneeded emails when one is setting up a meeting. It seems like however they are generated when changes are made during a meeting - which seems unneeded since minutes are generated.

**Comment by agilepro** [comment]
The description is correct.

Email about comments is controlled by whether you subscribe to that topic or not.  The initial subscription list is set by the person who posts the topic.  This setting will have no effect on comments.

Meetings is a different thing.  If someone sends a reminder about a meeting, it is not affected by this setting.
