### ISSUE TITLE
Comment form: reorganize action buttons

### ISSUE THREAD

**Issue by iangilman** [agilepro/cognoscenti#19]
It should always be clear what the primary action is. Right now both "save & post" and "save draft" have the same visual priority. I recommend "save & post" have a special look so it's clearly the primary action. One possible layout would be for both "cancel" and "save draft" to have the same visual style, and for "cancel" to go against the left side of the dialog and "save and post" and "save draft" to go against the right.

**Comment by agilepro** [comment]
To me, the options "save draft" and "save & post" have equal importance.  I don't see one being primary over the other.  If you have been typing for a while, it is important to save.  If what you have written is in a "done" state, you might go ahead and post it, but if not quite done, maybe a draft is a better option.  I don't see one as being more primary.  It just depends upon whether you are ready to let others see it or not.

Cancel however is a very different thing, and you will be throwing away any edits, and there is no way to recover if yo do that accidentally.  i expect Cancel to be used rarely.

**Comment by iangilman** [comment]
The problem is that having the two save buttons look almost identical and be right next to each other creates cognitive load… Now instead of just hitting the button instinctively, I always have to read them and think about which one I want. Friction like this is what makes an otherwise pleasant app seem like a chore. So, even if they are of equal importance, some effort should be made to make them more distinctive, to avoid placing this cognitive load on the user and allow them to operate on instinct (once they've learned the buttons).

That said, I don't agree that they are of equal importance. I have never once used "save draft", so from my perspective as a user it could just go away and I wouldn't miss it. If "save & post" was removed, I'm sure everyone would miss it; it's the whole point of the Topic page. 

Your reason for needing "save draft" is that it's important to save every now and then, but why is that? Presumably to protect against power failures and glitches. If the app itself periodically saved a draft without you having to click a button, that would accomplish the same goal without introducing more work for the user.

From an accidental click standpoint, "save draft" is also potentially problematic, if the user thinks they have posted the comment, and yet it's only a draft. It's not as dramatic a situation as cancel, but it can still feel like data loss in that you said something and no one has seen it. I think we've already seen situations where @johnabuck thought he posted a comment but it was just a draft, and he didn't recognize the visual distinction or didn't understand the difference.

Anyway, at the very least, it should be easier to tell the difference between the buttons.

**Comment by agilepro** [comment]
Well, OK.  Let's give it a try.  The next version (should be put up today) will have the "draft" buttons the same style as the "cancel".  See if that is OK.  We could make a third style, but I would like to avoid that unless necessary.

**Comment by iangilman** [comment]
I agree that having a third style would be confusing. I think the new look is an improvement. I still like the idea of also positioning the cancel button on the far left so it's physically separated. That helps enhance the visual hierarchy and avoid accidental clicks. 

Speaking of accidental clicks, perhaps cancel should have a verification dialog, to avoid accidental loss?

**Comment by agilepro** [comment]
assigned to Sven.  Would like to get his input on this.

**Comment by slatzel** [comment]
Hi there, for me the two buttons are also always a friction. Even that I know the meaning of both of them and their position, I have to carefully read them. What we can try to make that a little easier is to remove the cancel button and instead add an X button at the top right corner, It's a window so why not closing it like one. And if there are unsaved changes a warning shows up.
Additionally I would change the wording of the post button to simply "Publish" and give it a more alerting color because it is the main action.

**Comment by iangilman** [comment]
Seems worth a try!

**Comment by slatzel** [comment]
The first changes are done.

+ modal title shows current action
+ replaced "Save Draft" button with status bar like link in the left lower corner that allows saves without closing the dialog, it leaves a drft in the draft state
+ only a Cancel and a Post button are left in the footer
+ Post button is always changing the state from Draft to Open and leaves the other states as they are
+ added warning if you want to cancel dialog with unsaved changed existing

Next step is adding a 30 seconds autosave functionality.

**Comment by slatzel** [comment]
Autosave every 30 seconds is now added too. For now I think it is ok, but we should rethink the whole state handling. Right now there are four different variables who are responsible for the behavior, it's a little odd.
