### ISSUE TITLE
Comment 5 - Personal Workspace Settings

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#190]
Regarding Roles You Play

1) I'm not clear about the relationship between this list of roles and the list of roles that appears when I click Roles in the magenta side bar. For example, in Personal, if I unclick Representative role it appears below in Roles You Don't Play. However, if I remove my name from the Representative role in the description in Roles, it appears in Personal as Roles Request Pending. 

2) Suggest changing "Roles You Play" to "Roles You Play In This Workspace".  It was not obvious when I first read it - I had to think, "Does this mean all the roles I play in every workspace" - the extra words would make it clearer.

**Comment by agilepro** [comment]
Changed the text to "Roles you play in this workspace.   Also changed the layout so it is significantly easier to understand.

![image](https://user-images.githubusercontent.com/5544889/30253714-bb6d081a-963f-11e7-8bd6-a366221db083.png)
