### ISSUE TITLE
attendance list

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#191]
I sat in on the implementation circle for GalGael. Meeting was in Running mode. I entered my name and at one point the list showed 6 or 7 people. However, toward the end of the meeting I noticed that only two people were listed - not including me. I tried to re-enter my name but the system would not take it. In the screen shot, below, if I clicked add yourself, my email address would show up briefly and then disappear.
![image](https://user-images.githubusercontent.com/10082365/27338362-ee97f746-55a2-11e7-91af-1fbf1acf662a.png)

**Comment by agilepro** [comment]
Yes.  I think I know what this is.  Unfortunately there is a roundtrip time for updating this value.  And if two people update it within a certain period of time ... they can step on each other.  Let me look at it.

**Comment by agilepro** [comment]
I have addressed this.  Now it sends the person to the server, the server integrates the new name, and then sends the result.  This avoids the problem of accidentally removing people because you have an out of date version of the list, which is what happened with your meeting.
