### ISSUE TITLE
Time setting in IE

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#192]
I'm trying to set the next meeting for July 6 at 6:00pm EDT. I set it in the calendar, click apply, and hit the X to close the window. However, the time on the meeting wizard still shows staring at 0:00.

Also, there used to be a way to set reminder time. It was in minutes. Can't find any way now to set the reminder.

**Comment by agilepro** [comment]
After you pick the day, you pick the hour, and then the quarter of hour.   The description seems to say you set the date, but never set the hour and quarter of hour.  Is it possible that you clicked apply before setting the time?

**Comment by agilepro** [comment]
Complete new date picker resolves this issue, but leaving it here becasue there is a problem with IE that still needs to be solved.
