### ISSUE TITLE
unclear instruction

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#194]
In the Personal page there is a checkbox Receive Digest. The help statement says:
**You are receiving the digest for this workspace** 

If you request to receive the digest of changes, then a summary of the changes to this workspace will be included in the period email (daily, weekly, or monthly) that you receive. "

What is not clear is how do you set the period of notice? daily, weekly, monthly? There is no option given when you check the box, and it is not clear if this period of notice can be set somewhere else.

**Comment by agilepro** [comment]
Changed the text to:

If you request to receive the digest of changes, then a summary of the changes to this workspace will be included in the period email (daily, weekly, or monthly) that you receive.  Set the notification period in your personal settings.
