### ISSUE TITLE
action items only partially working

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#199]
Hi Keith, 
I just tried to assign an action item to Laura Latis in the GovernanceAlive Workspace. It only gave me Laura Basu even though I've been able to assign Laura other action items. 
![image](https://user-images.githubusercontent.com/10082365/28503344-94019982-6fd2-11e7-94f4-69d97f86c8ce.png)

On the details tab, the due date says i can't enter a date until the action item is completed, which makes not sense - particularly since I put a July 25 date into the Status tab. I'm wondering if these symptoms are related to the problems Marc (Arborlife) just reported.

![image](https://user-images.githubusercontent.com/10082365/28503365-370978a2-6fd3-11e7-802c-5422cd936916.png)

**Comment by agilepro** [comment]
I found and fixed the date issue yesterday, but the server won't be updated until tomorrow.

I know of a known issue with the cached people list.  I thin that is what you ran into with Laura.  I will be looking into those.  I am pretty sure it has to do with having cached a list, and then keeping that forever, so it does not know about new users.  Be sure to close your browsers and reopen to assure that the latest list is there.  I will see if I can get it to refresh automatically after a certain time.

**Comment by agilepro** [comment]
The people list is kept only 30 minutes.  

This problem might happen if you do it within 30 minutes of creating a user.  But that is unlikely.  There is no easy way to force the user list to be refreshed.  So as a performance trade-off I think it is best to leave this remaining unlikely problem in.
