### ISSUE TITLE
unable to enter comment

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#201]
In admin agenda item with meeting in planning mode, am unable to enter a comment. Can get this far:
![image](https://user-images.githubusercontent.com/10082365/28653015-379772c8-7259-11e7-89ef-0c00d1063f83.png)

But then I get a comment box that wont let me enter any text.
![image](https://user-images.githubusercontent.com/10082365/28653059-723515fc-7259-11e7-9e43-f9516bde0c10.png)

Same thing happens if I try to enter a Proposal

**Comment by agilepro** [comment]
This has to be a cache issue.  Please shift-refresh and check again.
