### ISSUE TITLE
no word wrap

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#203]
status box does not do word wrap for a long url. See worksite: John Buck experiment with Weaver for personal space

![image](https://user-images.githubusercontent.com/10082365/28700850-422bb4de-7320-11e7-9189-5c5259a7fb27.png)

**Comment by agilepro** [comment]
This is a basic browser problem.  You have a URL there, and there are no spaces, no place for the URL to be broken.  We should, however, be able to make the table cell clip the display so that it does not display out of the cell.
