### ISSUE TITLE
delay in task list update?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#204]
There seems to be a delay in posting action items on the overview display. 

I am experimenting with putting priorities on the action items in the synopsis so that I can filter them from the overall listing. For example, I put a "1." in the item "fix TSG website for Rita and Gonzalo" to read "1. fix TSG website for Rita and Gonzalo". After saving I clicked on the Weaver logo and chose Display All Items under the Action Items Box. I got the display shown below. I did a Shift-refresh and got the same thing. I added a 1. at the end of the synopsis to see if position had any effect. Now, 10 minutes or so later, it still won't display. 

![image](https://user-images.githubusercontent.com/10082365/28745711-d0264ebc-744b-11e7-9e75-0fa74be5000e.png)

However, if I go the the "John Buck experiment with Weaver for personal space" workspace, the synopsis displays just fine. (not this screen shot also shows the failure to wrap problem reported in an earlier issue)

![image](https://user-images.githubusercontent.com/10082365/28745750-7e158010-744c-11e7-8e15-ca56446a9948.png)

**Comment by agilepro** [comment]
Right.   The global list for all your tasks is refreshed daily.  There is a option menu it to refresh the page.   The point of this page is to take you to the item, but not necessarily to show the current name.  Usually task names don't change.

There is a feature that is intended to refresh the page when you make an action that changes something.   That mechanism is apparently not working.  

-keith

**Comment by johnabuck** [comment]
I found the recalculate page option and it works. How long is the lag time to automatically recalculate the page? I.e., when do I need to do a manual recalc and when not worry about it?

**Comment by agilepro** [comment]
It recalculate every 24 hours at the latest.
