### ISSUE TITLE
accidental minutes remain dangling pointer

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#206]
In trying to log the google minutes for the August 10 meeting I found that I could not remove the default minutes, even though I didn't create a minutes for the August 3 meeting. 

Actually before I thought about it I generated minutes of the August 3 meeting and then went into Topics and removed it. But the cloned meeting still kept it & so I'm not sure what other scenarios would do. In any case, I could not remove the default meeting minutes and replace with the item I added to Documents from the google record.

**Comment by agilepro** [comment]
When you generate it again, you will have the new minutes attached.  If you have deleted the old topic there is no problem.

The problem exists after you accidentally generate minutes, and delete the minutes, and before you generate the real minutes.   Can we live with that?
