### ISSUE TITLE
batch update of labels on multiple documents

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#209]
I just went through the WeaverMeeting Tech Board workspace documents and put labels on them. I wanted to add labels to several items but had to do them one at a time. Although one should really label as soon a document is added to the doc file, probably many people won't be so conscientious. Even if you're just adding labels to two files, it would be handy to be able to click the items in the list you want to add labels to and add the labels in one operation.

**Comment by agilepro** [comment]
This has been working for a couple years.
