### ISSUE TITLE
On return to editor, need to select text twice to use format or link buttons

### ISSUE THREAD

**Issue by rgilman** [agilepro/cognoscenti#21]
If I want to format the text or create a link, and move to another browser tab to, e.g. copy a link, when I return to the editor and select the text I want to work with, clicking on a format or link button does nothing other than defocus the editor. If I select the text a second time, I can get the formate or link button to work.

**Comment by agilepro** [comment]
switched to TinyMCE editor, please check if this is still a problem

**Comment by rgilman** [comment]
Doesn't seem to be a problem with TinyMCE.
