### ISSUE TITLE
meeting agenda items sequence problem

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#210]
Note on a glitch that showed up in the meeting today (Aug 10). On John's screen items would not rearrange in order but could be opened. this problem did not correct after refreshes or leaving the screen and coming back. Note: when John first came onto the meeting screen, there was a problem when clicked on running - rather than the running button, a message appeared where the button should be saying something about "State"

**Comment by agilepro** [comment]
this has been fixed
