### ISSUE TITLE
UI review on an actual online meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#213]
I just finished running a circle meeting online with a group of people that I am mentoring and was observing with "UI review eyes" as the meeting progressed. This is a different kind of UI testing because I was observing use in an actual meeting. Next time I will record so that you can observe. (we meet at 6:15am my time & so not a good time for you to be there live)

The feeling of the interface is still one of "fragmentation." For example, the person taking minutes wanted to look at the whole agenda but she couldnt do so without closing the minutes box and then re-opening it after her quick glance. If I jumped out to a list of action items, I would feel confused about how to get back to where we were. If I'd done a few entries with the action items, I'd have to hit the back key several times to return. Or, sometimes I'd screw up something and then have to go to the meeting list, open the meeting, and then find where we were. When the minute-taker wanted to say something in a round, she'd have to close her minutes. I would open another minutes box to take notes while she was speaking. Then she would open another minutes box when she resumed her duties. Some of that may be helped when we get the google drop-through feature.

**Comment by agilepro** [comment]
minutes are now in a separate window.  I believe this addresses the problems noted here.
