### ISSUE TITLE
problem posting minutes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#215]
Problem reported by user Rita Tojal. See email sent Aug 20. Screen shot:

![screen shot 2017-08-17 at 13 01 14 1](https://user-images.githubusercontent.com/10082365/29494839-e0ab4fda-8580-11e7-8745-5ca4db9baa06.png)

**Comment by agilepro** [comment]
This is the result of a performance optimization.  A list of all the known discussion topics is downloaded once and reused.  In this case, generation of the minutes creates a new discussion topic,  Pressing the "back" arrow takes you back to a page that does not know about the new discussion topic, and so it warns that it is missing, when it is not.  Better cache invalidation is needed.

By the way: hitting refresh on the page would solve the problem.  Not that we should require this of user, but it is helpful to know this solution.
