### ISSUE TITLE
item time

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#219]
from Rita Tojal

last time when I set up the meeting on WEAVER it was easy and I didn't find things to change. Only one small suggestion. When trying to change the time of each item on the agenda, to change the amount of minutes I had to go into a specific item. Would it be possible to just click on the number and change it right there?

**Comment by agilepro** [comment]
Implemented this.  The time numbers are displayed in editable controls that allow you to change them as desired before creating the meeting.
