### ISSUE TITLE
Button should be "Select Topic" not "Change Topic"

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#22]
The blue box that says "Change Topic" should read "Select Topic"

**Comment by agilepro** [comment]
I assume you mean in a Meeting Agenda Item where a topic can be associated.  What if you already have a topic selected and associated with that agenda item?

**Comment by rgilman** [comment]
Can the system change the button title based on whether there is already a topic selected? If not, how about calling the button "Select or Change Topic".

**Comment by agilepro** [comment]
OK, i did that.  It say "Set" when not set, and "Change" when it is set.
