### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#220]
When i try to log into weaver I get this screen:

![image](https://user-images.githubusercontent.com/10082365/30140907-d11225da-9345-11e7-9b7a-d927b7540e08.png)

**Comment by agilepro** [comment]
Generally refresh the browser.  This sort of thing can happen when the protocol to log you in gets partially completed, but not completely.  If you can figure out how to reproduce this I would be able to look into solving the problem,
