### ISSUE TITLE
problems using the edit meeting menu and timer 

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#222]
In meeting with some interns this morning we tried the edit meeting feature and the timer. There were sync and refresh problems - see documentation in these meeting recordings:
https://youtu.be/yKQTgSlQR8A
https://youtu.be/Tz4mDreRQII
https://youtu.be/7HpmF2Nz2Z8

Summary of problems encountered:
1. I had a refresh error on my screen and couldn't see the meeting page, but the other two users (in Portugal and India) could see it. I finally did a Shift Refresh and could see the page.
2. Timers didn't sync. When I moved to item 3 from item 2 clicked on the #3 timer, Umesh's timer on item 2 kept running and eventually went red. When I clicked on the #3 timer in the Weaver meeting page, it responded correctly in the Edit Meeting page but not in the primary page. 
3. typing again in the Edit Meeting page caused an error condition.

4. When we gave up on the edit meeting page, I shifted us to using Edit Agenda Item and took notes there (because Minutes was no longer an option). I closed the box,  & then Rita stepped into the same item to add notes. My notes were on here screen as she added notes, but when she closed the box, only the notes she had written were saved.

5. After I cloned the meeting, I found that I could not delete the notes that had been taken in the Edit Meeting mode.

**Comment by agilepro** [comment]
This was caused by lock contention when everyone was trying to get the meeting state at the same time.  I have an optimization that takes care of this.
