### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#223]
just now tried to enter info into Comment box of an agenda item for todays Weaver Board meeting. Then decided to delete box. There was a response delay and then this error showed.

![image](https://user-images.githubusercontent.com/10082365/30436821-228b1606-993b-11e7-8108-2582f358e8f6.png)

**Comment by agilepro** [comment]
I believe this was caused by a group of people fetching the meeting state at the same time and causing lock contention.  I have an optimization that I believe takes care of this.
