### ISSUE TITLE
email problem

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#224]
fowarding this message from a member of the Certification Mentoring workspace.

Hi John,

I recently came to know that when we set action item  as a completed , WEAVER is sending multiple email saying that this task has been completed. I am receiving minimum 3 email for the same action item saying that it has completed. 

This is just to bring your  attention to it.

Best,

Umesh Mangroliya

**Comment by agilepro** [comment]
I checked the records.  This actually happened because he did three different things, and got three different email messages.  The email was slightly delayed, so he got them all at once.  Closing because the original concern that that there were three email messages for one action was not the case.
