### ISSUE TITLE
odd message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#225]
I got the following strange message. don't know what I did to trigger it.
![image](https://user-images.githubusercontent.com/10082365/30747103-2c19df5a-9f7a-11e7-8ac1-70bba7f003d4.png)

**Comment by johnabuck** [comment]
It just happened again. I was in the old system. I have both instances open.

**Comment by agilepro** [comment]
This had been caused when you leave a browser open, and put the machine to sleep, wake it up (or otherwise disconnect from the Internet for >30 minutes) and it would flash this warning.   The message is actually harmless.   I changed the code so that it no longer makes a visible warning.
