### ISSUE TITLE
UI prob

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#226]
On new server, new workspace, tried to set up a new meeting. Clicked on Options and got. Couldnt scroll over otherwise figure out how to get to full display of dropdown box. Clicked on the corner and got a new meeting format. Needs to drop down & not sideways.

![image](https://user-images.githubusercontent.com/10082365/30818518-c8012bfa-a1e9-11e7-8f06-adae9d16a1f1.png)

**Comment by agilepro** [comment]
I found and fixed this!!!
