### ISSUE TITLE
fetching data message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#231]
when i tried to set up the Edit Meeting Notes function a few minutes ago, I got this message for about 30 seconds before I got the display correctly.

![image](https://user-images.githubusercontent.com/10082365/31434983-068719fc-ae4c-11e7-9c0d-ec38afa6e7db.png)

**Comment by agilepro** [comment]
This is the correct behavior.  The amount of time you wait depends on the number of notes and how quick the network is.

I made a change to abbreviate the amount of data by approx 10x to speed up this page.
