### ISSUE TITLE
paragraph 

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#232]
Looking at the minutes of the Certification Mentoring Workspace, in the new flat file we took notes on the closing round. A single Return started a new paragraph for each person. However, in the minutes it appeared as just one long paragraph. In parts of the meeting where we did 2 returns, the paragraphing structure survived.

Is there any way to preserve the single Return paragraphing when the minutes are generated?

**Comment by agilepro** [comment]
What you are typing there is "markdown" and you need a blank line (two returns) if you want it to be a new paragraph.
