### ISSUE TITLE
strange screen display

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#234]
I just sent an email to the member of the Certification Mentoring workspace. I soon as i sent the email, I got this display (& nothing else showed on the screen):

![image](https://user-images.githubusercontent.com/10082365/31440991-cf45af4e-ae5f-11e7-967a-f61a136798e6.png)

**Comment by agilepro** [comment]
There was an error on the page that showed the list of prepared email messages.  This was caused by the big edit over the weekend making sites movable, and able to provide a forwarding page.  Fix will be uploaded very soon.
