### ISSUE TITLE
slowness of topics

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#238]
It's probably not surprising but using Weaver in India, I notice that Topics (in the Weaver Board workspace) are taking a long time to load. Much longer than any of the other magenta column items. Action Items, the next least responsive take maybe three seconds to load. Topics seems to sit for about five minutes "Fetching topics." When I go away from the page and come back and refresh a few times, the list finally appears. If I try to click on a particular topic, it may not display the first time, but will upon clicking a second time.

**Comment by agilepro** [comment]
I have made a change that significantly improves the speed of the main "topics" page.  On workspaces with lots of topics this reduced the size of download by 10x
