### ISSUE TITLE
error in quick reply test

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#242]
I clicked on Email Discussion Support Video in the test of email replies and got this error message:

![image](https://user-images.githubusercontent.com/10082365/33350413-a55884ee-d46c-11e7-8820-43325b039013.png)

**Comment by agilepro** [comment]
a character was missing in the URL composition.  This is fixed.

In the future, if you can, whenever you get error accessing the site, include the URL that you clicked on because that is key to understanding the problem.
