### ISSUE TITLE
initial log in failures

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#247]
Received this email today about login failure.
Hi John,

i haver tried to log in but the password is not valid.

This for me is a big effort, to engage on another online platform. I will consider this a sign to confirm my initial feeling when i red this email, so i won't participate on weaver for now.

i hope this doesn't hurt your feelings but mine are very intense right now and have to protect myself a bit.

talk to you soon,

Bernardo

--------------------
De: John Buck <john.buck@sociocracyconsulting.com>
Enviado: 2 de janeiro de 2018 02:53
Para: bernardosn@hotmail.com
Assunto: Invitation to Collaborate

Hi Bernardo,

This message follows up on the Weaver demonstration session I gave several people at the Sociocracy Workshop. It certainly took me much longer to get Weaver set up than I intended!! 

This message invites you to participate as member of the workspace called 'Portugal Workshop Participants' Conversation Area'. If you click on Documents in the magenta column on the left side of the page, you'll find a link to the Weaver Youtube Channel. It contains detailed instructions about many Weaver features. Also, feel free to open topics for discussion with other members of this site (it may take me a few days to load everyone). Also, thanks for any Feedback! You will be copied on any discussions that others initiate. 

I've invited everyone who attended the Weaver demonstration at the workshop (+ you & Rita) to join this workspace: 'Portugal Workshop Participants' Conversation Area'. You can see this list of members/invitees by clicking on Roles in the magenta column. Then click on Members. You can add other members. 

You will also receive a separate invitation to a workspace with your name.

The links below will make registration quick and easy, and after that you will be able to participate directly in the workspace.

If you have any challenges, email me at john.buck@sociocracyconsulting.com or text me at 1-410-245-8654 (especially if I don't respond right away to your email).

John

Click on this link or copy the following address into your browser:

https://interstagebpm.com/eid/?openid.mode=validateKeyAction&registerEmail=bernardosn%40hotmail.com&registeredEmailKey=PDA-KX-TVU-PA-PGH&app=https%3A%2F%2Fs06.circleweaver.com%2Fweaver%2Ft%2Fsocio%2Fportugal-workshop-participants%2FfrontPage.htm

Your confirmation key is PDA-KX-TVU-PA-PGH.

If you don't know the persion who made the request, and you are not aware of the project you can safely ignore this message. It is possible that someone entered your email address by accident.

**Comment by agilepro** [comment]
John, there is no mention of a password in the email.  He has to SET a password.

It is possible he was confused about the confirmation code.  I have been thinking about simplifying this message.  I think we can assume that links work in the current world, and I can do away with the parts that are designed to help people when links don't work.

**Comment by agilepro** [comment]
I am simplifying the email to simply say "click to SET YOUR PASSWORD"

I think this is clearer because no person will be confused into thinking that a password is being sent to them, and they will not take the confirmation key and try to use it as a password.  

There is some tiny possibility that someone will not be able to receive simply HTML email, but lets see if that ever happens.

![image](https://user-images.githubusercontent.com/5544889/34551974-45407ff2-f0d3-11e7-9161-70415007974d.png)
