### ISSUE TITLE
another initial password failure

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#248]
here is another initial password failure that happened a month or so ago. It was just called to my attention today:

Annewiek Reijmer jreijmer@sociocratie.nl via stsociocratischcentrum.onmicrosoft.com | Annewiek Reijmer jreijmer@sociocratie.nl via stsociocratischcentrum.onmicrosoft.com | 11/8/17 |   |  
-- | -- | -- | -- | --
Annewiek Reijmer jreijmer@sociocratie.nl via stsociocratischcentrum.onmicrosoft.com
to John | to John
to John

Hi John,

I have tried to get in, but didn’t succeed. I tried it with your password and also asked for a new one. Both didn’t work.

Please help.

Gr.

A’wiek

Unable to log you in to user id (jreijmer@sociocratie.nl) with that password. Please try again or reset your password.Email Address: User ID from LDAP Directory Server:Password:
--
Register for free account   \|   Reset your password Note: Enter your email address and password. If you have never set up a password here for your email address then use register for free account.If you have forgotten your password, use reset.
----------------------------
Van: John Buck [mailto:john.buck@sociocracyconsulting.com] 
Verzonden: zondag 5 november 2017 10:33
Aan: Annewiek Reijmer <jreijmer@sociocratie.nl>
Onderwerp: Invitation to Collaborate

Hi Annewiek, 
I propose to use Weaver to get all of our information about marketing in one place. This message invites you to the 'Global General Circle' workspace.

The links below will make registration quick and easy, and after that you will be able to participate directly with the others through the site.

You can go to the discussion by clicking on Topics in the left margin, magenta colored. The "Marketing" topic is currently in the picture forming stage. I've already posted various messages that I collected from our various email strings,

If you click on Documents, you'll see a link to a Weaver YouTube channel where there are instructions about Weaver features. (Or, I'll be glad to show you how it works.)

John

Hi Annewiek, 
I propose to use Weaver to get all of our information about marketing in one place. This message invites you to the 'Global General Circle' workspace.

Click on this link or copy the following address into your browser:

https://interstagebpm.com/eid/?openid.mode=validateKeyAction&registerEmail=JReijmer%40sociocratie.nl&registeredEmailKey=RXL-YB-CCR-AJ-ZFH&app=https%3A%2F%2Fs06.circleweaver.com%2Fweaver%2Ft%2Fsocgroup%2Fglobal-general-circle%2FfrontPage.htm

Your confirmation key is RXL-YB-CCR-AJ-ZFH.

If you don't know the persion who made the request, and you are not aware of the project you can safely ignore this message. It is possible that someone entered your email address by accident.

**Comment by agilepro** [comment]
I clarified the message to make it clear that you have to set the password, and included a note that the message is good only for 2 days.  (internally there is an additional day buffer, however give time zone differences some people think 2 days and 1 hour is still within 2 days.

![image](https://user-images.githubusercontent.com/5544889/34552024-b5994e3c-f0d3-11e7-9b00-4554f5f1b9f5.png)
