### ISSUE TITLE
no bcc

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#255]
I recorded this message in the Weaver topic system. Am also putting it here for your tracking purposes

Keith,

Here's another nuance that's popped up.

I'm preparing to start teaching an online advanced facilitation class. I'm going to use Weaver for the class. I was about to send a message to everyone welcoming them to the class and introducing them to Weaver. However, then I realized that I don't have their permission to share emails with the other class members. I'm pretty confident that no one will have any problem, but I have run across people in the past who get prickly about just making assumptions about that.

So, I'm going to send the initial message using bcc and then switch to Weaver. However, I'm wondering - in a Weaver message does everyone see everyone else's email address? I think so because I don't remember seeing a bcc function. And, I also don't think it's worthwhile adding that feature because normally there would be no need for it.

However, I'm just logging the wrinkle.

John

**Comment by agilepro** [comment]
Email is ONLY sent to the recipient.  There is an individual message sent to each person, so the normal problems with people seeing the TO list is not there.  The only address on the TO list in the email is the recipient.  

However, if you log into the site, and are a member of a workspace, then all the other members can see your email address.  We should discuss whether this is a problem or not.

**Comment by agilepro** [comment]
discussed.  This is rare and there is another workaround:   let them know in the invite message.
