### ISSUE TITLE
stop the clock

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#262]
In the note-taking form that one reaches by selecting Edit Meeting Notes, you can start and stop the clock. However, in the meeting agenda itself, there is only a way to start the clock on an item - no way to stop it except by starting another clock. 

Today in the Facilitation class, I did not use the simultaneous notes form - only the clock that shows on the agenda. I couldn't stop the clock when I wanted - eg when we took a break.

**Comment by agilepro** [comment]
there is stop now
