### ISSUE TITLE
member role ueber alles

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#264]
In the Facilitation class, I signed up two guest instructors in a guest instructor role only - not as members. I just found out that one instructor has registered but she could only get into the Front page of the workspace and could do nothing else. Just a note to myself that everyone always has to be a member. We might want to change later - but as I noted in an earlier issue, i don't see an urgency to change it now.

**Comment by agilepro** [comment]
inviting members has been revamped since this was written and I think it addresses this problem
