### ISSUE TITLE
where did save and preview go?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#266]
I partially wrote a note to the class about the agenda for later this week. Then, I clicked Save and Preview and opened Meetings to check something on the agenda. When I came back to the email page, the note I had partially written was not there. It had actually not saved. Would be very convenient in such situations to be able to save emails in draft form

**Comment by johnabuck** [comment]
I just found the draft in the Email Prepared file. Shifting the draft to the Email Prepared file made it disappear. Encourage some sort of breadcrumbs so the trail can be followed. Eg the save button could say, "Save as Draft to Email Prepared"

**Comment by agilepro** [comment]
Looks like the problem was returning to the edit page again.
