### ISSUE TITLE
Can we warn when Internet is lost?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#267]
I wrote a couple of paragraphs on a comment and went to post it and got this message:
![image](https://user-images.githubusercontent.com/10082365/47571785-62c6e300-d907-11e8-85d7-b93cf17f71fd.png)

So I lost everything I'd typed. I was unaware that I had lost internet connection (was using a phone hot spot). Is there anyway to warn that you've lost internet connection? I would have saved what I wrote if I was aware I was about to lose it.

**Comment by agilepro** [comment]
Difficult to work around the network disappearing.  Still, would be good.
