### ISSUE TITLE
doc not downloading

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#269]
my guest instructor tried loading items for the documents list but when you try to open them you get a 404 error such as:

![image](https://user-images.githubusercontent.com/10082365/47611499-46c55d80-da3d-11e8-9adb-8fe4898cf4ba.png)

However, she was able to load a google file address

**Comment by agilepro** [comment]
Problem seems to be that links and google documents (which are links) are not handled when you choose "download file" directly from the meeting or topic.  These either should be handled correction (redirect browser to the URL) or the menu should be removed.
