### ISSUE TITLE
for closing round

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#27]
This is a request not a bug report.

Several meetings ago I started keeping the closing comments from the past two or three meetings and added comments from the current meeting. That let us see the trend in comments from any particular member. Is it possible to do that automatically? See for example the closing round for the December 4 meeting.

**Comment by johnabuck** [comment]
Suggestion: make it so that you can see who else is on a document. More or less the same way you can see it with google doc

**Comment by agilepro** [comment]
Yes it is possible.  Make a discussion topic in the workspace called "closing round" and then make the closing round of the meetings refer to that discussion topic.  Then, comments from each meeting will accumulate on the discussion topic across all the meetings.
