### ISSUE TITLE
email list not reflecting member role list

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#270]
Went to send out a message about the meeting for Session 3 of Adv Facilitation course. Email list reflects old membership list:
![image](https://user-images.githubusercontent.com/10082365/47763843-bd11cc00-dc98-11e8-8084-96a38b4ea77b.png)

Not the current membership list:
![image](https://user-images.githubusercontent.com/10082365/47763875-de72b800-dc98-11e8-9392-01aa225161ae.png)

**Comment by agilepro** [comment]
The names that appear in the TO box by default is the "Meeting Participants" which was set when you POSTED the meeting.  Later you change the "Members" Role.   This does not change the existing meeting that you have posted.

You have two choices:

(1) just send email to "Members" even though they are not participants of the meeting.   Pick the role above the TO box, and click the button.  Here is a MEETING with two participants, even though the members role has a lot more:

![image](https://user-images.githubusercontent.com/5544889/50554454-7e37cc80-0c6f-11e9-9d4c-cabd2b81b665.png)

Click on SEND EMAIL and get this:

![image](https://user-images.githubusercontent.com/5544889/50554464-acb5a780-0c6f-11e9-94d0-a6da7d94a8de.png)

Select "Members" in the role box:

![image](https://user-images.githubusercontent.com/5544889/50554473-d40c7480-0c6f-11e9-87d7-0d3fa4066272.png)

Click the button to add them:

![image](https://user-images.githubusercontent.com/5544889/50554480-eedee900-0c6f-11e9-8f81-b6e8d9936e88.png)

That should do it.

(2) the other option is to update the list of participants to have everyone from Members.
