### ISSUE TITLE
round

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#272]
tried again to do a round in the closing round box. People were able to open the descriptor box, but when they posted what they had written, it disappeared. 
![image](https://user-images.githubusercontent.com/10082365/47881269-04fd3400-ddfc-11e8-8335-efdb3a7f6ba8.png)

![image](https://user-images.githubusercontent.com/10082365/47881292-15adaa00-ddfc-11e8-98ca-492cc9e535d8.png)
after i click save, the whole box disappears

**Comment by agilepro** [comment]
Oh! that sounds really bad.  I will look into this.
-Keith
------------------------------------------------------
Keith D Swenson
408.859.1005
http://social-biz.org/

**Comment by agilepro** [comment]
This is now addressed by the check-in today.
