### ISSUE TITLE
safety message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#274]
clicked on one of the Weaver tabs I've had open - it pretty much stays open day to day and got this message:

![image](https://user-images.githubusercontent.com/10082365/48014754-67ed1480-e0f5-11e8-8c78-0381d491beac.png)

**Comment by johnabuck** [comment]
tried restarting Weaver and got the same message

**Comment by agilepro** [comment]
I think I updated the certificate on Nov 3.  I don't understand why you still had it on Nov 5.  Anyway, it is certainly working now.
