### ISSUE TITLE
cursor jumping around

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#276]
Here is a note from topics in the Facilitation Class. I had noticed my cursor jumping around and thought it was me or a poor internet connection in India. However, Bernadette is also reporting it:

![image](https://user-images.githubusercontent.com/10082365/48989397-0d454800-f0f8-11e8-9bbc-80495c158717.png)

**Comment by agilepro** [comment]
now there is an orange warning of merging changes.
