### ISSUE TITLE
give reminder note on scheduling changes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#280]
Per a user incident in the Facilitation Class: 
"From Mukunda Das to Everyone: (16:05)  John, I made a mistake. I accidentally erased the Jan. 10th date for the next meeting. When I added it back again, other people's availability didn't come back. Sorry!"

Solution: if a user tries to delete a date in which other users have inputed date responses, have the system give a message, "Really mean to delete? All user inputs will be lost." If there are no entries, allow the delete to take place without the user information.

**Comment by agilepro** [comment]
This is implemented and will appear on the server at the next refresh.

If nobody has registered any votes for a time, the row will immediately delete.  But if there are user votes, it will prompt for a confirmation before deleting the row.
