### ISSUE TITLE
where is "email pending?"

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#283]
I added a Comment to an agenda item for our meeting on January 2 because I wanted it as background info. I decided that I didn't actually want it to send an email (or wanted to amend it). I clicked on Email in the left magenta column but couldn't find any mention of the email under Prepared, and there was no category that said "Email Pending." Yet, the system says "Email Pending"
![image](https://user-images.githubusercontent.com/10082365/50456146-8cf54b00-0920-11e9-9c00-bc9fd665a5fb.png)

**Comment by agilepro** [comment]
![image](https://user-images.githubusercontent.com/5544889/50554187-fe0f6800-0c6a-11e9-9f5c-70af01447fb4.png)

Let me know if you can find this.
