### ISSUE TITLE
another example of pasting problems: spacing and indenting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#285]
In this case I pasted a Word document (from MS Office 2008) into a Comment box in a Topic. The original Word version looked like this:
![image](https://user-images.githubusercontent.com/10082365/50553456-08cefa80-0c75-11e9-889a-2bebb211448b.png)

What got pasted looks like this (spacing and indenting problems):

![image](https://user-images.githubusercontent.com/10082365/50553474-8266e880-0c75-11e9-9944-42fc618efa91.png)

**Comment by johnabuck** [comment]
In this case, spaces were added rather than being removed.

**Comment by agilepro** [comment]
Two answers:

(1) Formatting is not preserved.  It attempts to recognize bullets, and heading, and it will preserve italics and boldface styling.  If recognized, it will then display those elements in the style of Weaver with particular styles that Weaver assigns to headers and bullets.  This keeps all the pages of Weaver looking consistent.

(2) It depends on how word has formatted it.  For example, even though some of the bullets appear indented, they also appear the same, which might be an indication that Word did not really consider them second level bullets, but actually first level bullets that had been indented.   I have seen before cases where I had maybe 8 bullets, and half of them were actually marked as a bullet, and the other half came out as normal paragraphs with a bullet at the front.  Word can make a normal paragraph look like a bullet, and a bullet look like a normal paragraph.   You can see a list of things in word that appear the same, but are actually styled differently.

All that being said, it correctly identified the bullets, each bullet has all the text expected, it identified the bold on the first bullet, and it identified the header style.

I decided to try myself: I made a word text like this;

![image](https://user-images.githubusercontent.com/5544889/50553902-9efb2480-0c65-11e9-80f5-75e0ee009db1.png)

And pasted and got this:

![image](https://user-images.githubusercontent.com/5544889/50553904-b2a68b00-0c65-11e9-8016-8d5190310d33.png)


This is wrong!   the last point is supposed to be at the main level, so I took a look at the HTML that Word sent, and it is this:

![image](https://user-images.githubusercontent.com/5544889/50553917-cd78ff80-0c65-11e9-84cc-24247a358fc3.png)

That last line is simply wrong, and it is wrong before the TinyMCE editor got it.  There are going to be problems with paste from Word that just can't be solved, I believe.

**Comment by agilepro** [comment]
Then I tried a tool on the web for converting word to HTML.   I pasted the same Word in, and got this:

![image](https://user-images.githubusercontent.com/5544889/50553951-758ec880-0c66-11e9-9f8e-37114003a296.png)

Which looks considerably worse.

**Comment by agilepro** [comment]
I went to HTML-Online.com which has an online HTML Editor, and pasted the same text into it, and got this:

![image](https://user-images.githubusercontent.com/5544889/50553975-f057e380-0c66-11e9-81be-549118eaf2ea.png)

Here, you once again see the main level 3 in the wrong spot, because Word actually generated the wrong HTML for this piece of text.

**Comment by agilepro** [comment]
Another online HTML editor got the same thing:

![image](https://user-images.githubusercontent.com/5544889/50553999-66f4e100-0c67-11e9-999f-04115e1f4bf2.png)

**Comment by agilepro** [comment]
different editor now
