### ISSUE TITLE
inviting to meeting refinement

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#286]
The step of specifying who will be in the meeting when setting up the meeting is now much smoother. (eg add all button)

However, when I go to post the meeting, I get all the names of all the members automatically filled in on the message. Could it just default to the people specified to be in the meeting?

**Comment by agilepro** [comment]
I can't reproduce the problem.  If I make a meeting with 6 participants, when I go to post, those six participants are in the list, even though the role "Members" has many more.  I am not getting it automatically defaulted to the people in "Members"
