### ISSUE TITLE
action item popup?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#289]
I notice in taking minutes that if an action item comes up in a conversation, it is very awkward or impossible to hop away to the Action Item form, write the item, and then return to taking notes. Ideally, I would be able to highlight some text, click on something or do a keyboard combination to tag it as an action item, put a persons name, and then return to typing. I could fil in all the other informaiton later.

**Comment by agilepro** [comment]
action item is fully displayed in meeting now.  and topics
