### ISSUE TITLE
meeting cloning moaning

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#29]
If I clone a meeting and then change the title, all the cloned items disappear.

**Comment by agilepro** [comment]
I am not able to reproduce this problem.  Are you sure that you did not forget to click on all the check boxes to include the items.  

Here is what I did:
1. Created a meeting with 3 agenda items.  Saved, verified that this meeting exists and it remains consistent by itself.
2. Chose "Clone meeting" from the options button at the upper right.
3. Clicked on the three check boxes selecting the agenda items
4. typed some characters into the spot for the meeting name
5. Pressed the "Create Meeting" button

all the selected agenda items were there in the new meeting with the new name.  If you are able to reproduce this problem, lets have a quick shared-screen meeting so I can see what you do.

**Comment by johnabuck** [comment]
I'm not able to replicate the problem. My line of thought was probably: "create the meeting and then I can see what cloned items i want to keep and not. Knowing that I made that mistake, at some point we might want to but in a logic check:  if user clones a meeting and then tries to save the meeting without keeping any of the cloned items, then display message box: "Do you want to retain any of the items you cloned?"
