### ISSUE TITLE
Prep of topics

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#293]
It's not clear if I can create a new topic and also enter several Comments before sending out the Topic to everyone. My impression is not (but I could be wrong).  I can show you where that was a problem in my facilitation class.

**Comment by agilepro** [comment]
Let me understand the scenario.  You are right that the current design assumes you want to send the main topic to everyone before making any comments.   Why don't you put the comments directly in the topic description?  

I think you can put comments on a topic that is still in draft mode, however I am not sure whether email is sent, and if so it would probably be confusing.  If it worked correctly would that be what you could use?

**Comment by agilepro** [comment]
To make this more clear to the user, I have now made the comment dialog have TWO post buttons:  Post with Email, and Post without Email.    When you have a draft email message, if you press Post with Email, it will certainly send an email for this comment.   If you press Post without Email it will suppress the email, but still make your comment available to people who visit the page.

THEN, I tied this to the underlying state of the Discussion/Meeting.   If the discussion topic is still draft, then you can create a comment, but you will only have the Post without Email option.  We don't want email messages going out about comments on a topic that has not itself been posted.   This way you can create a bunch of comments, but only without sending email.   THEN when you post the overall topic, the comments will be there (or Rounds or Proposals).  

Same with meetings.  While the meeting is in draft, you will be able to create comments, but only Post without Email.  Once the meeting has been itself posted, you will be able to have the choice of posting with Email, and you still have the Post without Email if you want.

This helps make it clear to the user exactly when the email is and is not being sent.

I also changed save to be "Save Draft" when the comment is still in draft, and then just "Save" after the comment has been posted.

This shows the new buttons:

![image](https://user-images.githubusercontent.com/5544889/51395353-83ab6880-1af1-11e9-83f0-6f656c8c2806.png)

**Comment by agilepro** [comment]
Comments are not sent TOGETHER with the topic note.   So you should POST the topic before adding any comments.
