### ISSUE TITLE
erase table

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#297]
If I copy an email into a comment, I get a table. I can't figure out how to delete the table

![image](https://user-images.githubusercontent.com/10082365/51088869-269b6580-1733-11e9-9200-5bd18fb789c6.png)

**Comment by johnabuck** [comment]
The body of the message is fine

**Comment by agilepro** [comment]
Just save it (as a draft).   Saving converts HTML to Markdown.   Markdown
does not support tables and will clear it out.
-Keith
------------------------------------------------------
Keith D Swenson
408.859.1005
http://social-biz.org/
