### ISSUE TITLE
rework for scheduling

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#303]
I had five names and four dates in the meeting scheduler and then decided to change the dates to the following week. I deleted all the dates but the names disappeared too. 

The system wont take names until at least one date is entered. 

Is it possible to separate name entry and date entry so that they are independent of each other?

**Comment by johnabuck** [comment]
also. once a name is entered and captured, suggest that you remove it from the data entry box. It's confusing to see it remain there. Also, how about also allowing date entry by pressing Return (Enter)?

**Comment by agilepro** [comment]
the names are now the names of invited people.  This used to be separate, but no longer
