### ISSUE TITLE
upload files bug

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#306]
When i upload a file and the uploading is complete, I get this sort of statement. However, when I click the DONE button in the righthand corner of the box, nothing happens.
![image](https://user-images.githubusercontent.com/10082365/51581633-df317980-1e96-11e9-8a9f-8763dd31473a.png)

**Comment by johnabuck** [comment]
The DONE in the screen shot is actually in the lower right corner but it actually on this screen appears on the lower right corner

**Comment by agilepro** [comment]
clicking on done does not do anything
