### ISSUE TITLE
error message doing a search

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#314]
I was in the Board workspace in Topics and did a search on "channel" and got this:
![image](https://user-images.githubusercontent.com/10082365/51939086-a20c4080-23dc-11e9-9eb7-c6742adefcf8.png)

**Comment by agilepro** [comment]
Server now has 2GB memory.  I have done a number of searches, and everything seems to continue.  Let me konw if anything like this happens again.
