### ISSUE TITLE
slow response on need to respond

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#32]
I have been trying to clear my Need to Respond items. After I clear them, it takes them several minutes sometimes to disappear from the list, making it hard to know whether the system actually took my response. Delay, also happens on "Need to Complete" items

**Comment by agilepro** [comment]
RIGHT.   I investigated, and found that it can be infinitely slow -- there are some cases where the page never gets a notification to recalculate itself.  The page should always be reconstructed every 24 hours, but you don't want to wait that long.   As a stopgap measure until I can find out why the event is not being received, I have implemented a manual "page recalculate" that will allow you to manually force it to display the latest results.
