### ISSUE TITLE
show calculated ending time for meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#323]
On the main meeting agenda the time cumulates with each agenda item. However if I am trying to calculate the time to finish at 10:00, the last entry might say 9:55 (5 minutes) So when I make a timing change in an earlier item, I have to calculate if the meeting is still ending at 10:00. It might for example say 10:00 (5 minutes) and whoops, I'm 5 minutes past 10:00 - but I have to calculate that. Suggest that there be an additional figure always after the last item on the agenda showing ending time. Eg,  9:58 (5 minutes) (Ending time 10:03)

**Comment by agilepro** [comment]
I have added the display of when the meeting is expected to end according the total of the set durations of the agenda items to the main meeting page.   It appears in two places, one at the top and one at the bottom.
