### ISSUE TITLE
can't add a set of names

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#327]
I am adding about 12 people to the new North Carolina workspace. I tried to copy in the list of email addresses (carefully prepared with a comma and a space after each address) but the role creation wizard takes them all as one address. I have to copy and paste each address separately. ;-(
![image](https://user-images.githubusercontent.com/10082365/53294952-c5998f80-37be-11e9-9bea-6c070b645c6f.png)

**Comment by agilepro** [comment]
this is fixed
