### ISSUE TITLE
not sending out meeting announcements

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#335]
I have scheduled a reminder for a meeting. But is not sending.

![image](https://user-images.githubusercontent.com/10082365/53815117-01ef8d00-3f2f-11e9-9730-1fbfd384d768.png)

I tried to send out a specific email, but has a really delayed schedule. (Feeling urgent because meeting happening tonight.)

![image](https://user-images.githubusercontent.com/10082365/53815211-382d0c80-3f2f-11e9-9ca3-0d1012bcb01b.png)

**Comment by agilepro** [comment]
I believe this is related to the server memory issue.  Email was not sending.  I rebooted the server, and it started sending email.  Can you confirm that the reminder for the meeting was actually sent?
