### ISSUE TITLE
more notes from 1:1 mentoring meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#337]
again got a chance to observe someone learning the system. Two more observations:

1. Kim had gotten on to Weaver about two years ago & was unaware of the training videos. Suggest that we put another item in the purple column saying something like Help/Training & have it link directly to our youtube channel. As it was, I had to hunt for the channel URL and give it to her. She would have probably looked at it on her own if there had been a clear link. Once I showed her the Weaver basics, she liked it.

2. In topics, if I display a round and choose "no email", I just see my name and it's not clear how I change to display everyone (although I do see in retrospect that I can go to edit and then responders - Although I don't understand the comment in grey that "You can add people here, but removing their name here will have no effect." (What does "have no effect" mean?). 

In the Meeting menu, however, clicking "Create without Email" gives a full display of everyone immediately - not just the originator. (I.e., two different results from the same button). Would like the display in Topics to be the same way. 

3. There is no way to remove a topic once you've initiated it. Only to unsubscribe. If everyone is unsubscribed, does that mean it is removed?

**Comment by agilepro** [comment]
1. training is int he purple left column
2. did an exploration, looks OK
3. found the "trash" menu item

all ok
