### ISSUE TITLE
break time is broken

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#339]
Break time doesn't work because as soon as you click proposed to add an item to the agenda, the item hops above the Break line. That makes it impossible to schedule the break like the other items.

**Comment by agilepro** [comment]
You need to make sure that "proposed" is not checked.   All of the proposed items are at the bottom below the accepted ones.   Break time appears the same whether proposed or not.   But you can edit it, and uncheck the "proposed" box and you should find it working normally.

I think the usability problem is that proposed items are not clearly separated from the accepted items.  I could also make breaks automaticaly accepted, however the same problem still exists for agenda items.  I think I will remove the arrows on proposed items, and instead display "accept" button.   Once accepted, you can then set the position.  I think that will make things a lot clearer.

**Comment by agilepro** [comment]
I have addressed.

(1) Break time (spacers) can not be proposed.  If you set it to break time, it will automatically unset proposed if it was set.   

(2) Agenda items which are proposed will no longer have up and down arrows.  Instead and ACCEPT button appears in that place.  You have to accept them before you can position them.   This makes them look enough different that I think fewer people will be confused.
