### ISSUE TITLE
system down?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#340]
when i try to open Roles, I get this message
![image](https://user-images.githubusercontent.com/10082365/54132592-e121ae80-43ea-11e9-931b-cf04df419e3b.png)

**Comment by agilepro** [comment]
OK, that was a file rights problem on the new server.   It happened only on a newly created user (that is a user who was invited and then actually logged in by setting their password).   I reproduced the problem, and verified that it is now fixed.
