### ISSUE TITLE
unable to add player

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#341]
I'm unable to add someone to my Advanced Facilitation Class. (Workspace in Sociocracy site)
Here's when I add:
![image](https://user-images.githubusercontent.com/10082365/54280391-c592e100-456d-11e9-8b08-b9ba295876c1.png)

Here's what it looks like after I close and then reopen

![image](https://user-images.githubusercontent.com/10082365/54280483-04289b80-456e-11e9-9206-371a42208ae6.png)

**Comment by agilepro** [comment]
This is what I am seeing:  
![image](https://user-images.githubusercontent.com/5544889/54289022-a85a1480-4565-11e9-801d-1d4c4d630bf3.png)
