### ISSUE TITLE
does timing default convey to agenda items?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#343]
I am preparing an online class with people from many timezones. The default start time for the first item is 8:30am - the correct time for EDT time zone. I have the impression that the start time in the meeting description at the top automatically adjusts for the user's timezone. Does it also automatically adjust the starting times for the first agenda item?

**Comment by agilepro** [comment]
There are two rules you need to remember.

1) Everything displayed in the browser is displayed according to the time zone that the computer is currently set to.   You usually set your computer to Eastern time, and you always see Eastern times.   You can easily verify this:  change your computer's time zone (this is in the OS, not a Weaver feature) and then look at the meeting. You might need to refresh the page.   All the times should be shown for the new time zone.   So anytime someone in India views the meeting, all the times will be in Indian time. This is all automatic and you should not have any problems with this.

2) Email is different.  With Email we have to compose text which is sent.  In this case, the time zone used is the one you set in your preferences.   You have Eastern set for your profile, so all your emails will be in Eastern time EVEN if you read that email in India.  If you change your time zone preference then, of course, it will not effect anything until the next email that is sent.  Email messages about meetings will have all the times in the time zone of their profile.

Most people fail to set the time zone correctly, so it defaults to California time.  There is a warning on the profile page when their time zone is set differently from their browser, however few people visit the profile page, and even so they don't always know how to set the time zone.

**Comment by agilepro** [comment]
new warning on the profile page -- when looking at your own profile page, and your browser is in a different time zone than set, you will get a warning.
