### ISSUE TITLE
multi-response box detail

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#346]
I am now getting topics submitted by my students in the Implementation Struggles Class - Keith you are a member. See Irena's posting. Challenge: I am unable to read all of her message as I write & I find myself wanting to refer to her text as I think what to write. It would be nice to be able to scroll it. (my work around is to open a second instance and toggle back an forth.) Here is what I see. I want to be able to scroll the top part - where her message is:

**Comment by johnabuck** [comment]
![image](https://user-images.githubusercontent.com/10082365/54524597-c00c1100-4948-11e9-9340-44112201dae4.png)

**Comment by agilepro** [comment]
This was a fairly easy fix.  Checked in and installed.
