### ISSUE TITLE
weird bug regarding links

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#348]
1. I wasn't there & so can't comment on what agreements were made or understood.
2. I do understand that there was a major shift in thinking which was to extend to all groups, e.g., Workshop Presenters, the same basic independence that IITI was requesting. With that shift, the new structure makes sense to me.
4. For example, the shift erases the distinction between the "community" and "IITI". The IRW is no longer there to serve the community and there are special provisions for the IITI - now it is IRW is there for everyone's convenience. The whole culture changed with the summit - no more control by board (eg no more required dues & no more structure to enforce dues collection) - only an organization that provides service to everyone if they want it. So the two pillar structure of bylaws that had been developed before the summit seems no longer applicable.

**Comment by agilepro** [comment]
?? Is this want you meant to put in there?   I am not understanding

**Comment by agilepro** [comment]
ooooops
