### ISSUE TITLE
really simple UI problems

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#349]
I continue to see how difficult it is for some people to grasp the interface. Toward the end of the Implementaiton Struggles training class (about 25 minutes before the end I think) someone confesses that he tried to create a topic but couldn't figure out how to get it out of draft mode. You can see it on the video.

**Comment by agilepro** [comment]
This is not a really simple UI problem.  I added more to the tooltip message that explains it takes it out of draft mode.

The video seems that something else was happening.  He was clearly ready to post, however for some reason you couldn't see it....   Maybe something else was going on?
