### ISSUE TITLE
transfer large files

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#350]
I can remember that we set up Weaver to be able to transfer large files. However, I cant remember how to do it. Please show me again. I have an example of a user who needs to do just such a transfer.

**Comment by agilepro** [comment]
Nothing special, just add the large file as a document.    Then use the send email and attach the document.   Should work for documents up to several hundred megabytes.

**Comment by agilepro** [comment]
Since this was just a question, and because it has been answered, closing this.  Reopen if the answer is not clear.
