### ISSUE TITLE
HELP! CANT TAKE ATTENDANCE

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#352]
tried to take attendance in Childrens Parliament workspace. Ran into compound name problem

![image](https://user-images.githubusercontent.com/10082365/54650851-a375f300-4a86-11e9-973e-1dbf7cbbafac.png)

**Comment by agilepro** [comment]
John, I made two changes.  First, some code to clean up and remove the entries that did not look like email addresses from the file that was storing those.  Second, I put stronger checking at the time that you input them:  it will really have to look like an email address.   

If you type something that does not look like an email address, it will DISAPPEAR.  There is no warning.  I don't know if that is jarring or not.  I would rather allow someone to correct it, however that correction was never possible in the past.  You have to enter it correctly, and if you fail you have to type the whole email address again.

If you type a list of email addresses it will parse it out (I put that in last week) but now it will check each element in the list, and only add the ones that look like email addresses.

I hope this completely clears up the email address entry problems.  Please let me know if you have any more problems.
