### ISSUE TITLE
small refinement

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#359]
It would be helpful from a UI standpoint if the flat file you see when clicking on Reply to this Comment had a somewhat smaller Reply box. For example, when I saw this display, I thought to myself "Gee, I wish I could see what comment I'm replying to - I guess I'll have to look back at the email." I didn't have any visual clues that I could just scroll down & did a scroll by accident.

![image](https://user-images.githubusercontent.com/10082365/56393965-df29e700-6203-11e9-9c3d-ffe99c5a14ea.png)

However, if the screen had displayed like this, I wouldn't have had that thought at all. I would have known there was more info to be had and scrolled down:

![image](https://user-images.githubusercontent.com/10082365/56394040-0f718580-6204-11e9-8ce5-e8b378d530d7.png)

**Comment by agilepro** [comment]
There was a time when Macintoshs had a "scroll bar" on the right.   the purpose of this was to give you an indication of how long the page was, and how far down it you had scrolled.  The current trend is to hide that.

I will make the edit box smaller.  The down side of this is that it is much less convenient to have to edit in a smaller box when your reply is more than a trivial one.   Yes, you can stretch it down.  

All you have to do is explore once, and you know that the rest of the thread is below, and from then on it should be obvious.   It seems unfortunate to optimize the UI for the first time user to the detriment of experienced users.  Still, it is important that first time users to be able to use it.    So, it will be smaller.

**Comment by agilepro** [comment]
dpme
