### ISSUE TITLE
Remove "See All" from home page items that aren't truncated

### ISSUE THREAD

**Issue by iangilman** [agilepro/cognoscenti#36]
Having the "See All" when you're already seeing everything there is sends the incorrect message that somehow something is hidden and creates anxiety.

If you still want people to be able to get to those dedicated pages, make the title of that section a link.

**Comment by agilepro** [comment]
Good point

**Comment by agilepro** [comment]
this is done.

**Comment by iangilman** [comment]
excellent :-)
