### ISSUE TITLE
limitation on some email wizards (this may be a repeat posting)

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#360]
I approved Miro Zaleta and went to the topic on automatic messages, copied the message and opened the Weaver email wizard to send a copy of the message to him. However, I ended up using regular email because there was no way to include a hyperlink in the message. 
This seems like a big impediment to the experiment in using Weaver to organize email conversations.

**Comment by agilepro** [comment]
in markdown, hyperlinks are created by putting them in [square brackets]   This works in email message bodies.

**Comment by agilepro** [comment]
This is a direct repeat of another so closing this
