### ISSUE TITLE
missing decision box

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#361]
It seems like there used to be a decision box at the bottom of the proposal round box. It now seems to be missing. I would like to have it back. The info in a Round or a Proposal likely contain instructions and background. I would like to be able to finalize the decision in separate language so that it then is the official decision.

**Comment by agilepro** [comment]
I have added a small empty box when the round/proposal is not yet finished.  Clicking on that box opens the editor for the "outcome" text and it closes the round/proposal.
