### ISSUE TITLE
need box next to Parent circle item

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#373]
When helping Mona today, I could see that there needs to be a data entry box next to Parent Circle in the Admin section. Mona didn't know to click in to the Parent Circle item because there was no box next to it, unlike the line below. Instead she clicked into the line below (Workspace Email ID) thinking that the box it contains must be the box intended for Parent Circle. Further, when I told her to click next to Parent Circle, she clicked too close to the text "Parent Circle" and thereby didn't land in the intended text box.

![image](https://user-images.githubusercontent.com/10082365/57975281-e45d8b80-7993-11e9-9833-33882517369b.png)

**Comment by agilepro** [comment]
Two changes to address this:

(1) you can click in the left column to activate editing.  Click on the words "Parent Circle" will start edit.
(2) added an inverse colored gray box indicating that a value is missing (when no value set)

result looks like this:

![image](https://user-images.githubusercontent.com/5544889/57976468-f04a4d00-7995-11e9-9100-644f7cd82756.png)

**Comment by agilepro** [comment]
Also: "workspace email id" appears only for sites with "experimental features" enabled.   We should probably not have experimental features enabled when training people.   Which workspace were you actually working on ?
