### ISSUE TITLE
oddity with decisions

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#377]
I posted Decision 4 in Imago Stewards, but it didn't display. I did a page refresh. Still no decision. So I opened another Record Decision form and posted again. This time it posted - but as Decision 5. What happened to Decision 4:

![image](https://user-images.githubusercontent.com/10082365/58443996-c8f52d80-80c3-11e9-8d2e-e21bb838dfda.png)

**Comment by agilepro** [comment]
This is what I am seeing:

![image](https://user-images.githubusercontent.com/5544889/58456087-1b404980-80d8-11e9-8b9f-649778249bd5.png)

**Comment by agilepro** [comment]
We need to keep eyes open and see if we can figure out what sequence of steps got that to happen.   Until we do that, this issue does not help, so closing it.
