### ISSUE TITLE
All Sites list not accurate

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#379]
I looked at the latest signup - Castagnois. All Sites list shows no WS. But If I open it, there is a WS that is named Test Site. Am not clear why this discrepancy.

![image](https://user-images.githubusercontent.com/10082365/58512474-2bedcf80-816b-11e9-99f5-fad1a07d1729.png)

**Comment by agilepro** [comment]
The statistics are calculated once per day.   the workspace had just been made on that same day.
