### ISSUE TITLE
Search "submit" button draws a lot of attention

### ISSUE THREAD

**Issue by iangilman** [agilepro/cognoscenti#38]
It's pretty common these days to not even have a button for search; I think most users know you can just hit return. If we do want a button, it could be much subtler. One approach is for the button to only appear once the user starts entering some text in the search field. Either way, it could be a little magnifying glass inside the right edge of the input box.

At any rate, as it currently stands, the "submit" button is the dominant design element on the top bar (besides the logo), which is out of step with its actual importance.

This might be something for Sven to tackle... I would tag him in this issue, but I don't know his GitHub handle.

**Comment by agilepro** [comment]
Yes, I agree.  I wanted a little magnifying glass icon, and it wanted it with no separation from the input box.  I just used the default from bootstrap and figured the detail style could be worked out later.   

Making it appear only after the input box gets focus is a good idea.

**Comment by iangilman** [comment]
Cool. 

Tagging @slatzel, so he can potentially work on it.

**Comment by slatzel** [comment]
I'm on it now ;)

**Comment by slatzel** [comment]
Hi, what do you think about this easy solution?
![image](https://cloud.githubusercontent.com/assets/19602040/16725869/f9822d0a-478b-11e6-986a-95096817a5f7.png)

**Comment by iangilman** [comment]
@slatzel Looks good! The magnifying glass icon could use to go down a pixel or two, but otherwise that's exactly what I was hoping for.

**Comment by slatzel** [comment]
@iangilman Done! It's one pixel lower now and checked in.
