### ISSUE TITLE
new item, running mtg

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#384]
(1) the create new agenda item button needs to be in the Admin agenda item where people are focusing  when thinking about additional items. Matt couldn't find the new item button at the bottom of the screen. 
(2) Attendance should be filled in automatically as people join the meeting. Matt was disturbed because my status was unknown because I hadn't added myself.  (this is only true for online meetings)
(3) The minutes I was taking in the flat file weren't showing because we were in Planning not Running mode. Could we put a reminder pop up message in once someone Opens Meeting Minutes that reminds me to turn the meeting to Running mode - or maybe do it automatically?

**Comment by agilepro** [comment]
This is done:  Could we put a reminder pop up message in once someone Opens Meeting Minutes that reminds me to turn the meeting to Running mode - or maybe do it automatically?

**Comment by agilepro** [comment]
UI is quite different now.
