### ISSUE TITLE
plan new meeting has confusing interface

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#389]
Meeting "doodle" is confusing. Because the initiator's picture shows up on the participants list and it appears that you can then just add more people. But the wizard won't accept a second person until the first possible time is posted. There is no intuitive process reason why you can't post the people and then the times or post the times and then the people. Ideally should work both ways. As an interim fix, suggest don't display the picture/initial of the originator until the time has been entered & grey the name feature until the time has been entered. The screen below caused confusion with user I was teaching (& I had forgotten about my perceptual challenge with this feature) (We got my name loaded but the Add Voter button would not respond.)

![image](https://user-images.githubusercontent.com/10082365/60191469-5aaaa480-9802-11e9-9d6f-b3928d9b93a1.png)

**Comment by agilepro** [comment]
This was too confusing before.   This is changed now to be exactly the meeting participants.  No longer any way to add people, you just get all the people you invited to the meeting.
