### ISSUE TITLE
one person, multiple emails

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#391]
I got the following message from one of the people using Weaver - part of my client body - she's a board member. Is there anyway to tell Weaver that one member has multiple emails that should be included in messages? In the mean while, I'm simply creating more members and assigning dummy names to that person

Hi John,

 

I’m wondering if you could also send emails to me to admin@relationships.co.nz and peter@relationships.co.nz.  Then if they send them on to me, I will hopefully get them.  I will also look at how to re-set my emails so they accept your mail.

 

Thanks,

Brenda

**Comment by agilepro** [comment]
Currently users can have multiple email addresses, but it only sends to one of them. 

What is the goal here?  Is ti to temporarily test emails?  If so, you can set up new users with those email addresses and add those users in when emailing.  They would be dummy users, but everything works.

Alternately, if she permanently wants to receive email at two addresses, I don't currently have an option other than create two users for her.

**Comment by agilepro** [comment]
John???  Any response?   We can set email to be sent to any ONE email address.   Will that do?

**Comment by agilepro** [comment]
closing.  This was a spam filter issue.
