### ISSUE TITLE
difficulty in accessing Weaver

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#392]
Reporting an instance of difficulty in reaching weaver. Brenda resides in New Zealand.

![image](https://user-images.githubusercontent.com/10082365/60407064-182cf300-9b87-11e9-882d-6e476b73ca43.png)

**Comment by agilepro** [comment]
ok.  good to know.  

not enough detail here to help in resolving anything else, so closing.  The server is running now, and as far as I can ell was running all the time the last few days.
