### ISSUE TITLE
markdown not working in action item description

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#393]
The mark up language is not working in description box for action items: Example: I tried to set up a bullet list in this example:

![image](https://user-images.githubusercontent.com/10082365/60437517-8a7bf280-9bdc-11e9-8a96-1627fb6efdca.png)

**Comment by agilepro** [comment]
And now it is:

![image](https://user-images.githubusercontent.com/5544889/63485474-60b2af80-c458-11e9-97c6-8e564455b29f.png)
