### ISSUE TITLE
wrong date on message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#399]
I approved a new site for a Dale Nunes and sent a Welcome message. However, I noticed that the date on the message says 31 Dec 1969. (see lower right corner of screen print, below)

![image](https://user-images.githubusercontent.com/10082365/61054706-008f0f00-a3be-11e9-9ef1-53a319417aac.png)

**Comment by agilepro** [comment]
It shows this date for a minute until the email gets sent.   This just
means "not sent yet"
-Keith
------------------------------------------------------
Keith D Swenson
408.859.1005
http://social-biz.org/
