### ISSUE TITLE
Links between decisions and their proposal

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#4]
At one time I found two different proposals that linked to the same decision ref number, but the two proposals were very different.  I believe the decision was No. 2.  (https://interstagebpm.com/av/t/socio/weaver-design-team/decisionList.htm)

[I wish we had easy referencing back to proposals.]  I will attempt to ID the two proposals this way:

1.  A proposal I made on 18 Nov 2015 under the topic: Terminology & structuring stories/manuals - (https://interstagebpm.com/av/t/socio/weaver-design-team/noteZoom0988.htm)
2.  A proposal Keith made 30 Oct 2015 under the topic: Weaver Decisions - (https://interstagebpm.com/av/t/socio/weaver-design-team/noteZoom0934.htm)

So yes, this 'bug' still appears to exist.  How did this ever happen is my first question?  I thought maybe it had something to do with that other major problem that wiped out our original decisions list.  Maybe the ref number 2 was not removed from the first listing to the first proposal and then when the list was regenerated it created a new ref to the old number.  

Regardless, the present database has the problem.  If I'm right then there might be two proposals linked to No. 1 too, but so far I have not noticed.

**Comment by agilepro** [comment]
There was a problem in early November that caused us to lose some data.  The October proposal was linked to a decision which was lost.  Later, on Nov 19, the new Decision #2 was created (again) and linked.  The problem that caused the data loss was related to (1) an improper multi-thread synchronization method, which was (2) exposed by a serious email performance problem.  These problems have been addressed.  There area  few dangling references but there should be no more created.
