### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#402]
See earlier issue - ever since I deleted my sociocracyconsulting.com email address from WeaverMeetingTech LLC Board workspace, I am unable to log in as administrator and can't get to many sites without using "backdoor" routes.

**Comment by agilepro** [comment]
You need to put the sociocracyconsulting.com email back into your profile.   Please do that, and then we can discuss the next step.

**Comment by agilepro** [comment]
I have deactivated the button allowing email addresses to be deleted.
