### ISSUE TITLE
more fallout from email deletion

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#403]
I can now log into Admin - thanks to your fix today. However, my watch workspaces function is blank.

Also, If I try to add my name as a meeting member in the CircleWeaver Board workspace (the Participants item), I type John and it doesnt recognize my name. when I enter a space, the John disappears. I am able to log me by saying add all members and then deleting everyone who's not invited.

**Comment by agilepro** [comment]
Whenever you change your profile substantially, you should close the browser and restart.   I assume the problem you ran into fixed itself a few hours later.
