### ISSUE TITLE
mysterious email transmission when posting without email

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#404]
when I created the meeting in Weaver for our call this morning, I clicked the button saying Post Without Email.  But an email went out anyway.

**Comment by agilepro** [comment]
New UI when posting meeting:

![image](https://user-images.githubusercontent.com/5544889/62400011-a56eb900-b532-11e9-927f-aa5d701b1290.png)

Tells about "Announcement Email" and tells about "Reminder" email

HERE is NO reminder set:

![image](https://user-images.githubusercontent.com/5544889/62400057-c8996880-b532-11e9-95a9-61f70379b838.png)

Here with meeting date set too close to now:

![image](https://user-images.githubusercontent.com/5544889/62400088-e2d34680-b532-11e9-8448-e59bb48c492c.png)

**Comment by agilepro** [comment]
If you check the send announcement now, then the button changes:

![image](https://user-images.githubusercontent.com/5544889/62400140-0ac2aa00-b533-11e9-8790-b6031212b1c0.png)
