### ISSUE TITLE
confusing email send dates

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#405]
I went to send new site requester a welcome email. Why does the record show two mailings in 1969 (not correct) and one on July 31, 2019 (correct - I presume you sent it?)

![image](https://user-images.githubusercontent.com/10082365/62262486-e659b700-b3e6-11e9-8bb2-f8019656f00a.png)

**Comment by agilepro** [comment]
This is an ADMIN page so I am assuming some technical understanding.

Dec 31, 1969 is "0" date.   When a date field is not set, it is set to Dec 31, 1969.  This is universal across almost all operating systems and computer languages.   Learn that this date is date zero and life will be easier.   (Actually date 0 is Jan 1, 1970 -- but in any time zone west of London this appears as Dec 31, 1969)
