### ISSUE TITLE
warning about Running

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#406]
We had an instance today where a new note takers was taking notes using the Edit Notes feature. However, the minutes were not appearing in the main agenda. It took me some poking around to figure out that the cause was that she hadn't set the meeting to Running mode. 

Recommend that if someone opens Edit Notes, they get a "heads up" message if they haven't set the meeting to Running mode.

**Comment by agilepro** [comment]
his is a good idea I have been thinking about, however it can be tricky.   Sometimes people want to enter notes before the meeting.   Most of the time, you want the meeting "running" when you take notes..   My compromise is to ASK and then automatically change the state.


(1) If meeting is DRAFT when you ask to edit notes:

![image](https://user-images.githubusercontent.com/5544889/62581573-7de35d80-b85e-11e9-9cb0-fa9ab4b25319.png)


(2) if the meeting is in PLANNING mode,  (or COMPLETED mode) then:

![image](https://user-images.githubusercontent.com/5544889/62581593-8dfb3d00-b85e-11e9-9981-4a7733753c69.png)


Click OK and it changes the meeting to running.   You are allowed to go there without running the meeting if you wish.   Hopefully, people will make the right choice.
