### ISSUE TITLE
format of dates

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#407]
suggest we put our dates in international format: YYYYMMDD.  ISO 8601 standard date notation.

Indian participant tonight was confused because the date read 8/7 and he read that as 8th July.

**Comment by agilepro** [comment]
Where did he see 8/7?

All the dates I know of are in this format:

![image](https://user-images.githubusercontent.com/5544889/62975756-f5217000-bdcf-11e9-965a-ce143439361d.png)

**Comment by agilepro** [comment]
if you find where that was, reopen the issue.
