### ISSUE TITLE
cloning: slight bug

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#408]
cloning does not move the participants forward

**Comment by agilepro** [comment]
No it doesn't.

What it moves is the associated Role.  The idea is that you use role management to maintain the list of the people who are supposed to be part of the group having the meetings.  Then, when you POST, you select from the members of the Role who will be at the particular meeting.

The effect of this is that if you add a member to the workspace, and if the meeting is based on "Members" then that new member will be optionally invited to the next meeting.

If instead we maintain meeting participants as a separate list of people, then when you add a person to the workspace, you will ALSO need to add them to the meeting.   A likely failure mode is when you forget to do this, then that person does not get invited or allowed into the meeting.  Having to add people in multiple places is a failure point.

So ... we can discuss in the meeting today.

**Comment by agilepro** [comment]
discussed, leave it this way for now
