### ISSUE TITLE
filter question

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#41]
I went to the topics list and searched on the word "bird" and got one hit on a topic written in 2015. I did not get a his on Sven's logo topic. 

Sven's logo topic has the word "fabric".  But, if I search on fabric, I get nothing. 

Is the word search feature operating properly?

**Comment by agilepro** [comment]
I am not having a problem searching for these terms "bird" and "fabric" and getting the correct response.  Please test again.  The results take a few seconds to appear.  Perhaps on a very slow connection longer, however this is not the likely problem.  PLease try again and see if it was transient.
