### ISSUE TITLE
another strange error msg

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#421]
I just tried to add a label to a document and got this error message
![image](https://user-images.githubusercontent.com/10082365/64832718-0b764380-d5a9-11e9-90be-4f3d4029ee17.png)

Here is the problem report
![image](https://user-images.githubusercontent.com/10082365/64832735-21840400-d5a9-11e9-8628-3ab49e077507.png)

Here is the Trace
![image](https://user-images.githubusercontent.com/10082365/64832748-31034d00-d5a9-11e9-96a6-8047ea418ba2.png)

**Comment by agilepro** [comment]
this is the problem of creating a workspace with the same name as an exsiting one.  I have installed the fix so this should never happen again.
