### ISSUE TITLE
workspace disappeared

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#422]
When I started developing workspace titled: Advanced Facilitation Class Fall 2019, I was imitating a workspace called Advanced Facilitation Class Fall 2018. However, that workspace has now disappeared. Can't find it anywhere.

**Comment by agilepro** [comment]
Did you try to create a new workspace named "Advanced Facilitation Class Fall 2019"   ???   

Maybe this is what caused the glitch that confused Weaver into thinking there were two workspaces with the same name.  advanced-facilitation-class-fa and advanced-facilitation-class-fa-1.    Note that for the name only "Advanced Facilitation Class Fa" is included, and the 2018 and 2019 is clipped off.

I will experiment some more, but I think maybe this is what caused the problem: creating another workspace with a very similar name.

If you don't want the things that are in the 2018 workspace, you could just take the "Friday 13th Workspace" and rename it to what you need.   Delete the other.

**Comment by agilepro** [comment]
OK I found it.   Creating a new workspace with the same name as an old workspace created the problem you experienced.  Weaver got confused between the new and the old workspace, inappropriately updating the wrong one sometimes. 

I have made a fix to avoide this problem.
