### ISSUE TITLE
search in google files

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#423]
I tried to find files a google folder. I did a search and got the folder I wanted
![image](https://user-images.githubusercontent.com/10082365/64833645-c0f6c600-d5ac-11e9-9527-025d144c86ac.png)
But when i clicked on the folder icon on the right to get a subfolder, this is all I got

![image](https://user-images.githubusercontent.com/10082365/64833688-dec42b00-d5ac-11e9-8821-de962edd8307.png)

However, if I just scrolled down the list and picked the folder
![image](https://user-images.githubusercontent.com/10082365/64833749-17640480-d5ad-11e9-8d43-91504f16e852.png)
I got the full subfolder I wanted, and a subsubfolder below that

**Comment by agilepro** [comment]
Yes, probably the filter is STILL applied in the subfolder.  I suppose it should be cleared so that it shows all the files....

**Comment by agilepro** [comment]
The simple solution with the existing code is to just clear out the filter.  You can clearly see that it is still filtering on "Ga Ad".   Click in there, backspace, and they all appear.

I never considered that anyone would use a filter to find a folder, but clearly it is done

I can make it clear the filter when you navigate down.  Hopefully that is what the user wants.

I have checked in the change, and put it on the server.  Please try again and let me know if that works the way you want.
