### ISSUE TITLE
carriage return bug

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#429]
In this text box (agenda item) I cloned the meeting (Portugal Workshop workspace) and was doing edit Description. If I dropped the cursor at the left side of the S in the first row and pressed Return, nothing would happen. 

![image](https://user-images.githubusercontent.com/10082365/65176029-f6266c80-da21-11e9-8eeb-35d411f9bc5c.png)

But dropping the cursor to the right side of the S produced this result (i.e., Return function was working fine.)
![image](https://user-images.githubusercontent.com/10082365/65175859-b1023a80-da21-11e9-85d6-04c65caacf76.png)

I tried it a couple of times with the same results. ;-(

Five minutes later I tried it again and there was no problem.  ;-)

**Comment by agilepro** [comment]
Ok.  I believe empty lines at the beginning are removed.    If you place the cursor before the s and type anything else (any valid character) does it work.

I think it is only blank line at the beginning that are suppressed.

Keith
