### ISSUE TITLE
another dual title problem

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#430]
I uploaded a recording our our Session 1 class and titled it "Recording of Session 1". I then realized I had uploaded the wrong file and deleted it. I uploaded the correct file and titled it also "Recording of Session 1" and got an error message. I tried the same thing with different URL and description but same title but got the same error message. I am wondering if the system is looking in Trash at the titles.

![image](https://user-images.githubusercontent.com/10082365/65207909-5f79a000-da61-11e9-98a5-560e9bc91dc1.png)

(Note: I finally got the file to store by titling it simply "Session 1"

**Comment by agilepro** [comment]
Deleted files are not removed until you garbage collect.   Step 1 delete.  You can undelete if you wish.  Step 2 is garbage collect.  That is done on the site.  Maybe should add an option to garbage collect a single workspace.  But the error message mentioned here is correct: there was already a file with that name and the solution is to use a different name.
