### ISSUE TITLE
filtering decisions

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#431]
This is an observation and not an urgent request. I would like to be able to list all the items in the Decisions list by their Review by date:

![image](https://user-images.githubusercontent.com/10082365/65376818-a094ce80-dc72-11e9-88b3-ca860e17f79c.png)

However, the red Review By labels don't appear if I filter on the word "Review" The only thing that shows up on that filter search is this one:

![image](https://user-images.githubusercontent.com/10082365/65376841-e0f44c80-dc72-11e9-9098-68ae64fba547.png)

**Comment by agilepro** [comment]
New filter option "Only Overdue" limits the list to those that are overdue

![image](https://user-images.githubusercontent.com/5544889/181657731-2759fc37-36df-476f-a4b0-218ac9e0443d.png)
