### ISSUE TITLE
still having upload problems

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#439]
this attempt ended much sooner than the earlier one. The error message provided no details

![image](https://user-images.githubusercontent.com/10082365/65726645-8f3d2f00-e083-11e9-933a-1a1c3c58ab14.png)

NOTE: later in the day I was able to send the file via WeTransfer with no problems.

**Comment by agilepro** [comment]
It used to hold a workspace lock while uploading the file.   That would couse a number of conflicts to occur.  It does not specifically explain this, but it would remove some problems. 

Later you confirmed that you were able to upload large files.
