### ISSUE TITLE
more on the upload saga

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#440]
upload completed but I found this error message. Note that Umesh was using the same workspace (in India) while the uploading was happening on my end.. He got an error message.  Umesh sent by email a screen capture of the error message he got.

![image](https://user-images.githubusercontent.com/10082365/65735177-421d8500-e0a4-11e9-8191-209747b66e4d.png)

**Comment by agilepro** [comment]
I cleaned out 5 uncompleted uploads.  there were also two successful uploads, one was 700MB, and the other 1.5GB.  Large files.   The two successful ones looked fine, the five failures show that there were obviously problems.  All had timestamps on that day or so.

**Comment by agilepro** [comment]
The file mentioned in this error message was successfully uploaded, but something had timed out making the response problem.  

I made a fix a couple days later to assure that files are uploaded without holding the lock.  What was happening was that the long upload, taking several minutes, was locking everyone else out of access int he meantime.   The new code uploads completely without a lock, and then later renames the file.  In the last 3 months no problems like this.
