### ISSUE TITLE
deleted files showing up when I click the ADD button on agenda item

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#442]
Copy of msg sent by email

Doesn't look like problem is fixed

Specifically:
In text item (item 8) in advanced facilitation class 2019 workspace, I click the add button
image.png
and I get this set of choices & three of the first four are deleted items:
Session 2 is valid. 
However, these three deleted files show up (relics of the upload files problem):
GMT2019....
Session 2 recording
recording of Session 2

image.png

**Comment by agilepro** [comment]
Now confirmed working after restarting browser.
