### ISSUE TITLE
sending new topic by email does not post it

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#443]
a confusing point I just ran across

I created a topic in the Portugal Workshop December 2019 workspace and added a comment in Round format; then I selected the Send Topic By Email option, assuming that that action would automatically post the topic. I saw later when I returned to Topics that the item was still all yellow - that I also had to Post Your Round to get it out of draft form.

**Comment by agilepro** [comment]
I have made the "send by email" option show a warning if the note is not posted, and tells the user to post it first, so that they can not accidentally send email about an unposted topic.
