### ISSUE TITLE
UI comment

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#444]
I just noticed that if I click on the detail below an agenda item (in this case - "9:40 (10 minutes)", the item opens immediately for editing. Dont' know when that feature became available - but is great. I have been clicking on the agenda name itself, seeing the add button show up, and sighing realizing that I had to open the editing by pulling down the arrow down box & wishing the open with one click feature would be enabled soon.

![image](https://user-images.githubusercontent.com/10082365/66017484-138b1a00-e4a9-11e9-80c7-08eab67643af.png)

It is just not intuitive to click below an item to open the item. Any chance that the name of the item itself could also trigger a one-click opening?

**Comment by agilepro** [comment]
done
