### ISSUE TITLE
action item bug

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#446]
when I try to do an action item from the edit meeting notes page, I can open it and fill in the wizard, but nothing happens when I click Create Action Item.  This is new. Worked a few days ago

When i try to create an action item on the main action item page, I cannot get it to accept the name of someone with the assignment

**Comment by agilepro** [comment]
if did find a bug in the meeting page: newly created action items were not being displayed on the meeting page.  I have fixed this.   Not able to reproduce the other problem.
