### ISSUE TITLE
remove grey text upon text entry

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#45]
In the Meeting tab, with an open meeting, if I want to add a new agenda item, I click New Agenda Item and the wizard opens, the display including a Name: field with grey letters saying New Agenda Item. I click in that field and before I enter anything I have to erase "New Agenda Item." Request is that such instructional messages disappear when you click on them so that you can just start typing. (i notice that several fields are this way - but am not sure if all work that way.)

**Comment by agilepro** [comment]
checked in fix for this
