### ISSUE TITLE
no autofill

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#455]
Both Umesh and are were on the advanced facilitation class 8 agenda to plan it. I was able to enter my name in the Assign Person slot by just typing a few letters and clicking on the name on the list. 

Umesh, however, was getting no response. Here is screen shot after he typed my name. He then pressed Enter and my name appeared as it was supposed to.  He just wasn't getting a list of names.

![image](https://user-images.githubusercontent.com/10082365/68539943-b8c2c900-0358-11ea-81f1-622ae8f5980f.png)

**Comment by agilepro** [comment]
This is working now.
