### ISSUE TITLE
login in error message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#459]
Isabel logged in (I watched here do it on screen share). She got this error message

![image](https://user-images.githubusercontent.com/10082365/69368377-077d3680-0c68-11ea-90fe-61d5863b3ccb.png)

**Comment by agilepro** [comment]
This was just a wrong password.   NOW changed to show a nicer message:

![image](https://user-images.githubusercontent.com/5544889/79056966-c682c000-7c10-11ea-922b-68c6f39bc5d1.png)
