### ISSUE TITLE
notifying a circle member

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#46]
In setting up the Weaver Training workspace, I was in the roles tab and tried to contact one of the (fictitious) players by clicking on his name to get a dropdown box and selecting Send Invite. The message never came.  However, I was able to send an email by visiting the player's page and selecting Send Invitation.

**Comment by agilepro** [comment]
I can't reproduce this, and there is not enough detail to determine what went wrong, so closing.  if more details appear and you want to pursue this, we can re-open.
