### ISSUE TITLE
direct file upload not working

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#460]
I am trying to upload a file directly from my computer into the Portugal Workshop's Documents. Have put on a label and made a description but it doesn't appear in the documents list.

UPDATE: The item did finally appear - system was slow. However, it doesn't have its label.

**Comment by agilepro** [comment]
I did fix one problem with uploading in the pop up dialog on action items.   Otherwise not enough detail to reproduce problem.   I uploaded successfully with labels:

![image](https://user-images.githubusercontent.com/5544889/71646000-5a013800-2c95-11ea-9605-cc2077a17fd5.png)
