### ISSUE TITLE
UI challenges in board meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#461]
in the IRW Stewards meeting today we had trouble finding an email someone had sent from a topic because Topic emails don't show up in the listing of emails

It would be helpful to let anyone edit a comment as the default. Someone wanted to post two or three paragraphs of information in a Comment under and agenda but we needed to be able edit what she posted & so I had to tell her to post a Round

**Comment by agilepro** [comment]
I can't reproduce the topic email problem.  When you post a topic and send email, it DOES end up in the list of email.   Could you test that again?

![image](https://user-images.githubusercontent.com/5544889/71645911-e01c7f00-2c93-11ea-934d-48b1b9a1b17e.png)

**Comment by agilepro** [comment]
reopening for the edit issue

**Comment by agilepro** [comment]
Restrictions have been removed.  Anyone can edit any comment at any time.
