### ISSUE TITLE
Response after clicking Save

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#462]
I was orienting a new user, Orli Wahrman, to Weaver. (Necessary because she is a user with rather low computer literacy.) I was watching her via screen share. She entered "Test Comment" in the round and clicked Save. Nothing happened. I had her Cancel and we saw that the works "Test Comment" had actually been saved. 

I recommend that clicking Save close the data entry box so that the user doesn't have to click Cancel to leave the data entry box.

![image](https://user-images.githubusercontent.com/10082365/71414056-241fdc00-2623-11ea-894c-fee8db3635f4.png)

**Comment by agilepro** [comment]
I found this and fixed it.   The scary thing is that this bug was introduced in Nov 2018 and has been in the code, unnoticed, for more than 1 year.
