### ISSUE TITLE
grey pens

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#463]
in preparing next Weaver board meeting agenda to post, i was confused because I wanted to make an edit to the title but the Pen symbol was grey - which I interpreted as meaning not activated. (Although I was then able to activate it by clicking on it.

![image](https://user-images.githubusercontent.com/10082365/71685311-f0049380-2d65-11ea-8338-bcb272e4fea4.png)

In Contrast, in the agenda items below, the pens are not greyed and it is clear, therefore, that they are active.

![image](https://user-images.githubusercontent.com/10082365/71685383-2510e600-2d66-11ea-9119-9a281b8fb0ff.png)

**Comment by agilepro** [comment]
I made them completely disappear (white) so they don't appear disabled.   Let's see how that works.
