### ISSUE TITLE
undated old drafts

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#465]
I notice that we have some undated and apparently old drafts in the CircleWeaver Tech Board workspace. Would helpful if the date of the draft appeared somewhere near the garbage can so that it would easy to know if the draft should be discarded.

![image](https://user-images.githubusercontent.com/10082365/72093287-17b5a780-32e2-11ea-9c54-6657b5fdd6a5.png)

**Comment by agilepro** [comment]
The date is the date of sending, but drafts are not sent.  This would introduce another date.   If managed correctly there really should not be more than one draft at any time, and it seems odd to optimize the system for someone who creates lots of drafts without sending them.  This seems more like "TEST" capability.
