### ISSUE TITLE
question about question marks

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#467]
I just set up a new workspace and added members. Two of the members were shown as ? but the other (also with only emails - not previously registered) showed up with initials. Why the ? marks? (note: the open identifier box refers to the lefthand question mark.

![image](https://user-images.githubusercontent.com/10082365/72954836-bb359c00-3d67-11ea-9c84-35107f20279a.png)

**Comment by agilepro** [comment]
question marks show only initially when you create a user, and all the information about that user is not yet distributed around the system.   Upload a photo will certainly resolve this.
