### ISSUE TITLE
log in difficulty

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#468]
User is having login problems. Also forwarded an email about this problem. Here is the error message - unfortunately the message loses its formatting when copied. See the email:

https://s06.circleweaver.com/ssofi/

 Error Occurred{"error": { "code": 400, "context": "Accessing SSOFI main capabilities", "details": [{ "code": "Exception", "message": "Unable to log you in to user id (Orli Wahrman) with that password. Please try again or reset your password." }], "innerError": {}, "stack": [ "Unable to log you in to user id (Orli Wahrman) with that password. Please try again or reset your password.", " OpenIDHandler.java: modeLoginAction: 580", " OpenIDHandler.java: doGetWithSession: 286", " OpenIDHandler.java: doGet: 126", " OpenIDHandler.java: doPost: 167", " OpenIDServlet.java: doPost: 73", " HttpServlet.java: service: 661", " HttpServlet.java: service: 742", " ApplicationFilterChain.java: internalDoFilter: 231", " ApplicationFilterChain.java: doFilter: 166", " WsFilter.java: doFilter: 52", " ApplicationFilterChain.java: internalDoFilter: 193", " ApplicationFilterChain.java: doFilter: 166", " StandardWrapperValve.java: invoke: 199", " StandardContextValve.java: invoke: 96", " AuthenticatorBase.java: invoke: 493", " StandardHostValve.java: invoke: 140", " ErrorReportValve.java: invoke: 81", " AbstractAccessLogValve.java: invoke: 650", " StandardEngineValve.java: invoke: 87", " CoyoteAdapter.java: service: 342", " Http11Processor.java: service: 800", " AbstractProcessorLight.java: process: 66", " AbstractProtocol.java: process: 806", " NioEndpoint.java: doRun: 1498", " SocketProcessorBase.java: run: 49", " ThreadPoolExecutor.java: runWorker: 1142", " ThreadPoolExecutor.java: run: 617", " TaskThread.java: run: 61", " Thread.java: run: 745" ] }}

**Comment by agilepro** [comment]
This is an ugly message on the screen, but it only means they have not entered the correct password.

I used to have a better message, but I was having some problem with the logic and needed to see the error. I need to put it back together so that the page is not so scary. 

If they don't remember the password, have them do a password reset.

-Keith

**Comment by johnabuck** [comment]
See email. She reset her password and that solved the problem. I've asked her to reconstruct the sequence of her actions that led to the problem.

**Comment by agilepro** [comment]
This message has been changed so that it displays nicely on the screen
