### ISSUE TITLE
roles function is funky

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#469]
Something is wrong with the Roles feature. Here is the message I get when I click of Roles

![image](https://user-images.githubusercontent.com/10082365/73191548-a7868e80-40f5-11ea-8071-5f5519c17ffe.png)

Also, some of the roles are giving me question marks - 
![image](https://user-images.githubusercontent.com/10082365/73191624-cc7b0180-40f5-11ea-8ef0-0eb58c19a7d9.png)

& that carries over to action items:
![image](https://user-images.githubusercontent.com/10082365/73191698-e7e60c80-40f5-11ea-8ed2-6c0964434be4.png)

**Comment by agilepro** [comment]
This is a sideeffect of transitioning from one method of generating images to another.  I have addressed this issue, and should not be seen again.
