### ISSUE TITLE
quirk about the minutes layout

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#470]
If I select Full Detail from the minutes display dropdown, I do indeed get all the details - like the message from Florian pasted into the description.

![image](https://user-images.githubusercontent.com/10082365/73494220-1f68e900-4382-11ea-8516-39754f2840a1.png)

It shows Full Detail in the display at that point.

![image](https://user-images.githubusercontent.com/10082365/73494267-33144f80-4382-11ea-93bb-8eafe05a0d90.png)

However, if I click the eye icon to view it, and then leave the minutes display by using the back arrow, the display reverts back to MinutesDetail. 

Note: if I view the minutes and then go back to the meeting by clicking on Meetings (magenta column) and re-display the meeting then the Full Detail setting is retained

NOTE also that "Agenda Detail" gives the same level of detail as the minutes "Full Detail" - which is further confusion of the meaning of the terminology ;-)

**Comment by agilepro** [comment]
There is no longer an eye link to press and navigate.
