### ISSUE TITLE
more on minutes formats

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#471]
there are now three levels of meeting minutes
Minutes
Minutes Details
Full Details. 

It is not clear if Full Details refers to Minutes or to Agenda. 

Maybe we could use the mnemonic of 
Minutes overview
Minutes most details
Minutes full details

**Comment by agilepro** [comment]
Full Details was not designed as an alternative for minutes, but as a simple way to get EVERYTHING in the meeting in a single web page.   It contains minutes, but also all the other details of the meeting.   The idea behind this one is that it would be a way to possibly print everything about the meeting, or more specifically a replacement for the main meeting page.
