### ISSUE TITLE
no drop

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#478]
I tried to send you your K-1 form via Weaver. I did not load your K-1 into Weaver but rather tried to drop it into the panel from a Google folder. I could drag the file over the panel, but it would not accept it.

**Comment by johnabuck** [comment]
Duh.  I realized when I sent the K-1 via regular email that I needed to have given you a link not a file drop. Oh well. Forget this item.

**Comment by agilepro** [comment]
You can drag from the file system.  But you can't drag from a google folder.
