### ISSUE TITLE
confusing login process for new users

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#479]
Helped Forrist set up meeting with new users. Forrist said a complaint is that the login for new users is difficult. Once they registered and come back in for the first time, they don't know what URL to enter. Once they do enter, they just see a blank screen. There are no watched workspaces, etc. Requests that the watched spaces be automatically filled in for the site the new user has been invited to so that the home screen is not blank.

**Comment by agilepro** [comment]
Home page has "Accessible Workspaces" now which is all the workspaces that you have been invited as a member of.  New users, invited to a single workspace, will find it there.
