### ISSUE TITLE
Session timeout is not very graceful when saving text you have been entering

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#48]
I went to Weaver Sandbox to play around with Meeting features so I can better understand them. I tried adding an item, OK. Then I tried adding a comment and then a proposal. In both cases the text box came up and I entered some words. But when I saved, the comment did not appear. Nor did the proposal. I haven't found this problem in the Weaver design circle

**Comment by agilepro** [comment]
Problem with session time out.   If you sit on a page for 30 minutes, the server side of the session will time out.  But the UI will still allow you to pop up a dialog to create a comment or proposal, and when you click save, the error is displayed without a lot fanfare.   It looks like nothing happened.   And, you lose your submission.  This is bad.  It should:

- Make sure you have a session before starting the dialog
- Preserve you edits even if you lose the session
- Pop up a message if anything else fails.

**Comment by agilepro** [comment]
lost of work on this
