### ISSUE TITLE
Comments on new format

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#480]
1) The box you see when you edit the Presenter item on an agenda item has a big check mark. When we were assembling the agenda, placing the check mark in item two forced it to go above item 1 and we could not budge back into place with the down arrows. When we removed the check, then the arrows worked again. The items only showed ... instead of a number indicating their order. We later emailed the meeting. When we went back the problem had disappeared and numbers appeared by each item.

2) Could the start as well as the planned duration time also in the Edit view (which now only has duration time, not clock time)? I think I will facilitate from the edit - view not the Agenda view because that is where the timer displays. (will confirm after the meeting tomorrow.)
 
3) When I tried to indicate I would attend I got this error message:
![image](https://user-images.githubusercontent.com/10082365/77030991-b4e22b80-6976-11ea-8673-3bcfe0d3baca.png)

4)

**Comment by agilepro** [comment]
i believe these are all fixed
