### ISSUE TITLE
send minutes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#481]
new meeting display creates minutes effectively but it no clear how to send out the minutes afterwards to everyone - not where they are stored (not stored in topics) How search the minutes, for example. The old format used to ask, "do you want to send the minutes?"

**Comment by agilepro** [comment]
Just choose send email about meeting, and choose the minutes layout.  Try it.   There is no separate "send minutes".  Choose the 'save and preview' to see what it will look like before you send it.
