### ISSUE TITLE
various UX bugs noted over the past few days

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#483]
*going to meeting from diagram gave old format (I couldn't duplicate the error - saw it on Forrist's screen when he was screen sharing)
*request to default to Agenda not settings
*email reminder was not received by participants but the log indicated it was sent
*Someone had troubles logging into chrome - got error message. retried on Safari & was OK. Got kicked off & then Safari gave error message
*The representative description is wrong - how correct template?
*Decision line in topics decision round needs to be labelled
*On weaver "doodle" for next meeting - names not all showing up
Edit Start Time has a different editing convention than everything else - you have to find a button
*Can't open action items from Edit, they don't appear on the Agenda. Can only open directly from Minutes screen
*In the Edit screen, if you mouse over the blue ball you see "modify the attachments" message, but if you click on it you get an error message
*In Edit, if you click on the click on the up arrow you see "modify the attachments" message, but if you click on it you open the attachment. 
*When you are in Draft mode, there is a button that says Post Meeting. But if you click on Draft to move it to planning mode, the Post Meeting button disappears and you can't send an automated notice of meeting (with names pre-filled)

**Comment by agilepro** [comment]
- I think the rest of the places have been found and corrected
- default it to agenda unless the link specifically sys something else
- I can't do much about email not delivered by email system
- Role description can be changed if you send the desired text
- discussed decision line
- discussed doodle columns, UI has been improved
- action items can be opened now -- the standard link has been fixed
- modify attachment link fixed
- message changed
- POST button has been removed from meeting page
