### ISSUE TITLE
login in error message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#484]
I finally found this screen shot I mentioned in Forrist's meeting. It is the screen that one of the participants saw when she tried to log in. Here is the link to the screenshot:

https://docs.google.com/document/d/1rsuH6eTV6dD-Ugb8EB8xa1WHDjJl64b_uZKy02zahos/edit?usp=sharing

**Comment by agilepro** [comment]
Changed so that a wrong password will appear this way:

![image](https://user-images.githubusercontent.com/5544889/78506139-78f7e600-772c-11ea-9b23-408ce1fa446c.png)
