### ISSUE TITLE
put word "minutes" in Search. Got this error message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#488]
![image](https://user-images.githubusercontent.com/10082365/78597864-40373a00-781c-11ea-8c26-633072a229b2.png)

Tried again and got this message

![image](https://user-images.githubusercontent.com/10082365/78597920-53e2a080-781c-11ea-9dec-5a4bfa9a627f.png)

**Comment by agilepro** [comment]
OK.   A "lock" is used to keep the various people accessing the server from stepping on each other.  A person gets the lock, and does something (usually only a fraction of a second) and everyone else has to wait for that to be done.

Occasionally there will be an error that causes the lock to REMAIN in place, locking everyone else out for about 5 minutes.   The ultimate problem is whatever causes the lock to be HELD, and that happened withing a few minutes before you encountered this.

The problem has nothing to do with "search" particularly, you would get the same error no matter what you did.   I will scan the error log and see if I can see what caused this.

**Comment by agilepro** [comment]
*something* locked up the search index and it stayed locked for several hours.  Not sure what caused it, but I did find a block of code that would have allowed the lock to persist if an error occurred while processing.  Have added code to release the lock on error (I think -- can't be sure this was it).
