### ISSUE TITLE
save minutes as a file

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#489]
There was a request today in the Imago Stewards meeting that we be able to save minutes flat file as a document that can be uploaded to google or other storage location. Right now the only way to do it is to send yourself a minutes document as an email and then save that email file and then upload to google. 

(We had responded to their request to be able to email a flat file - which is fine - but their real requirement seems to be to be able save directly as a file.

**Comment by agilepro** [comment]
Follow the link to the "printable" version of the minutes, and use "Save As" to save it as a html document.   Reopen if this is not what you want.
