### ISSUE TITLE
Election wizard is gone

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#490]
I can open the election wizard in the circleweaver board workspace and in Planetary Care General circle workspace. However, for the Imago Stewards Workspace I get this error message even after I refresh the page

![image](https://user-images.githubusercontent.com/10082365/78851189-2f86ef80-79e7-11ea-9076-c1cb34fcf77d.png)

**Comment by agilepro** [comment]
ok, thanks.  I found this.   I occurred when you had NO terms defined, but you wanted to go straight to the elections of the current term.   Coding mistake.
