### ISSUE TITLE
can't save label

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#491]
If you upload a document from your computer (upload file) and
Once it is uploaded you add a label, you can't save the label because the Done box is in the way.

![image](https://user-images.githubusercontent.com/10082365/78852952-b1791780-79eb-11ea-8b93-f369cd3423af.png)

**Comment by agilepro** [comment]
The idea is that you set the label BEFORE you upload and it will be applied to every document you upload. THe idea was to be able to have labels set and automatically applied to documents that are uploaded.

Clearly you thought it would be the other way: upload first and then apply label.

The question is: NOW that you know that you should set it first, would you find it as easy to do that? Obviously you can go to the document list and set the label afterwards. I could make this window work like the other document list -- which is just a certain amount of work. But the question is that now that you know you should do it first, would that be sufficient?

-Keith

**Comment by agilepro** [comment]
Added clarification to the screen:

![image](https://user-images.githubusercontent.com/5544889/79056690-cd5c0380-7c0d-11ea-8d08-643018fd8bb7.png)
