### ISSUE TITLE
a puzzler: what happened to the meeting record?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#495]
After we finished our meeting yesterday, I started to clone the meeting to set up next weeks meeting. I got distracted and just left the meeting with the clone box open. I went back to it just now, and said to myself, "I'm not sure if I actually cloned the meeting or not" and hit the cancel button on the clone wizard. And lo and behold, the April 20th meeting had disappeared - even after I refreshed the screen. 
1) bad bug? I'm hoping you can replicate it in a test environment
2) Are you able to find the meeting notes in a trash can somewhere and restore?

This picture shows what the hole looks like - no April 20 meeting notes

![image](https://user-images.githubusercontent.com/10082365/79931839-f48ab000-8419-11ea-91dc-7b57f51fac5f.png)

**Comment by agilepro** [comment]
John,

That meeting list is from Imago Relationships. I think you are referring to our WeaverMeeting?

If you look at the WeaverMeeting Tech list, there is a meeting for April 21, and also April 28 (your new clone). We held the meeting on April 20, but it was actually scheduled for April 21 as was reported in the email message I received announcing the meeting:


Check the weaver meeting and see if it is all there.

-Keith

**Comment by agilepro** [comment]
No response, closing.
