### ISSUE TITLE
round box not included in minutes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#498]
I was taking notes this evening in Forrist's general circle meeting. Two of the agenda items had reports from several participants so I used the Round box to record their comments (to save having to record their names. However, none of this information appeared in the Minutes! Is there a simple way to include the box information in the minutes?

**Comment by agilepro** [comment]
There is no easy way now, but it is a good suggestion.

**Comment by agilepro** [comment]
yes this is supported
