### ISSUE TITLE
Cannot label in GitHub

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#5]
Can someone tell me how to label issues?  I tried to follow the help instructions, but I see no checkbox to check before attempting to apply a label.  Do I not have the right permissions?  Or am I just not in the right screen?

**Comment by iangilman** [comment]
We don't have the right permissions. @agilepro (Keith) might be able to change that for us...I'm not sure how granular the permissions are (i.e. if he can give us the power to label without also granting the power to change code). 

At any rate, I do think being able to label issues would be helpful, so we can keep the bug reports separate from the design issues.

**Comment by agilepro** [comment]
should be able to now
