### ISSUE TITLE
document names should not be allowed to have vertical bar character

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#50]
In the Document Tab, I notice that the article i added to the documentation list "Nets full of holes catch long-term memories | Science News.pdf" is not accessible if I click on it. It will not refresh from History.

**Comment by agilepro** [comment]
Another interesting bug!   FIle names are not allowed to have a vertical bar character in the name. If present the behavior is quite odd.

The uploader and other parts the prompt for document names need to clean this out, or else return an error.

**Comment by agilepro** [comment]
Checked in the fix, should be available on the site in a few days
