### ISSUE TITLE
link function not working

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#506]
This message is something I put in Settings. I set the link but when I click on it, it goes no where. If i just copy the link into a URL, no problem:  (see the Art of Facilitation Workspace Settings)

You can obtain a recording of Session 2 by going to this URL: 
https://us02web.zoom.us/rec/share/-Mt5dozJ7m1OHIWU2EjVVqR8E57Faaa81CMf_fFczx2I4SpdPbutBlIi2bDg-pKl

and entering the password: 4f%0e&%4

**Comment by agilepro** [comment]
Video no longer exists.   not enough context to understand the problem.   Don't know what "set the link" means.  where?  When?  What value?

"This message is something I put in Settings." -- you mean you put this message somewhere in Settings?  Where?

"I set the link but when I click on it, it goes no where." -- no idea what "the link" is

"If i just copy the link into a URL, no problem" -- OK, so just do that?

**Comment by agilepro** [comment]
This has been working for a couple years.

**Comment by agilepro** [comment]
no response
