### ISSUE TITLE
when I double click to get a green thumb, the other green thumbs around it turn red

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#510]
This was the result when I double clicked the green thumb in the break to turn it red, the icon below it turned from green to red also. Sometimes more than one green thumb in the area turns red. (I notice that there is no ready thumb in the breaks if viewed from Edit)

![image](https://user-images.githubusercontent.com/10082365/82109779-bf1a6f00-9706-11ea-833d-acbdea1d4dfe.png)

**Comment by agilepro** [comment]
cant reproduce.  assuming it is fixed.
