### ISSUE TITLE
not saving email

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#512]
When I partially prepare an email about a meeting and click Save and Preview and later go back to Email to retrieve what I saved, I can't locate the email. Have to write it all over again. Tried twice and the same thing happened each time.

Actually, it looks like even the sent emails aren't showing up on the email list. latest one shown is 1/30/202

**Comment by agilepro** [comment]
Was showing only 200 emails, and those were older ones.   Fixed this by always showing emails from the last year.
