### ISSUE TITLE
email prepared not sighted

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#514]
I just prepared an email about the latest Weaver Board meeting and hit Save & Preview. I then went to Email. Email Prepared appeared, but did not list the email I had just saved. 

![image](https://user-images.githubusercontent.com/10082365/83086931-0df8ca80-a05e-11ea-958c-b043a7c91128.png)

I tried opening some of them but none were the test message that I had prepared.

**Comment by agilepro** [comment]
There were six emails with the same subject line and I am not quite sure how you tell which is which.  I can't reproduce this problem.
