### ISSUE TITLE
what happened to Edit

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#515]
I am in a meeting and can see the Agenda. but Edit is completely blank

![image](https://user-images.githubusercontent.com/10082365/83439824-def1a880-a411-11ea-9c72-6bb93a75891d.png)

![image](https://user-images.githubusercontent.com/10082365/83439888-f597ff80-a411-11ea-9705-9c71051f6e8e.png)

**Comment by agilepro** [comment]
You have no agenda items.

Everything you are seeing there is part of the DESCRIPTION of the meeting. Somebody apparently took the entire minutes from one meeting, and copied them into the meeting description.

Here is the SETTINGS panel:
-Keith
