### ISSUE TITLE
can't add a document from my computer

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#52]
I could not load a .pdf document called Monster Chart.pdf to the Document list from my computer. I was able to load it as a google document.

When I tried to add from my computer, I could drag the file into the Weaver wizard and I even added a label. Then, there was no button for me to push to complete the process. I tried pushing various buttons including the Submit button up on the search bar, but nothing worked after 3 tries.

**Comment by agilepro** [comment]
Unable to reproduce this.  I created a document called "Monster Chart.pdf" and attached it to a workspace.
