### ISSUE TITLE
false need to respond

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#530]
I have these items that I cannot removed from my need to respond box on my home screen. I Can't find anything open about them.

![image](https://user-images.githubusercontent.com/10082365/97085608-75567e80-15ec-11eb-8a2b-1340f227372d.png)

**Comment by agilepro** [comment]
Even without your links I was able to find the first one just by looking around:

![image](https://user-images.githubusercontent.com/5544889/97957631-790ea180-1d60-11eb-923b-986bf783364b.png)
