### ISSUE TITLE
previous minutes not displaying

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#532]
When I click on minutes of previous meeting as in the top line of this screen shot, it just displays the minutes of the meeting I'm in. If I repeat it, then it just gives me the title of the meeting I'm in - not the previous meeting. (See second screen shot) Same thing seems to happen in other workspaces as well. 

![image](https://user-images.githubusercontent.com/10082365/97818859-ffe55080-1c72-11eb-8933-75dcca598484.png)

![image](https://user-images.githubusercontent.com/10082365/97819020-fa3c3a80-1c73-11eb-9528-5538fb17c953.png)

**Comment by agilepro** [comment]
I believe that was clicking on the wrong links and since there were a lot of meetings with almost exactly the same name it was confusing, but working correctly.
