### ISSUE TITLE
Something is wrong with markdown

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#535]
This is part of the email I composed to the participants in my latest online class.

Here is a link to the article I mentioned at the end of our class. 
![image](https://user-images.githubusercontent.com/10082365/98995774-d98ba480-24ff-11eb-9616-6b2655d7a02e.png)

This is how it was translated into the preview message:  
![image](https://user-images.githubusercontent.com/10082365/98995828-ee683800-24ff-11eb-87d9-50b7fcb09470.png)

Note that the preview message does not show the initial bracket: [  

Note that it removes the _ and turns it into bolding

**Comment by agilepro** [comment]
It would be REALLY REALLY helpful if you would include a link to the workspace, at least the name of the workspace.
