### ISSUE TITLE
bug in create a round

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#547]
when I try to create a round, it only shows one persons name even though there are several members. The other members have to be added manually one at a time. Seems like we used to have automatic fill

![image](https://user-images.githubusercontent.com/10082365/102441058-87064200-3fef-11eb-925c-2dcbc4974e87.png)

**Comment by agilepro** [comment]
This happens when you have a meeting with only one participant, or a topic with only one subscriber.

Once again, you need to send the URL of the page that has the problem so I can investigate.

Try adding meeting particpants, or topic subscribers.

-Keith
