### ISSUE TITLE
still cant remove parent circle ;-(

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#550]
After i click on parent circle and then click on the black Remove Parent button, it appears that the parent has been removed. 

![image](https://user-images.githubusercontent.com/10082365/104408394-eba2b700-5531-11eb-87ca-84dc3682193e.png)

However, when I leave and return to the Admin page, the parent has not actually been removed

**Comment by agilepro** [comment]
ok, required an engine change.   Got it now
