### ISSUE TITLE
can't enter new item

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#572]
I've been trying to add a new item to the next meeting of the Weaver Board circle. Tried about three times. When i save, the entry disappears. Weird. Never happened before. (See the phantom item 6)

![image](https://user-images.githubusercontent.com/10082365/122317984-6199b880-ceec-11eb-9ff1-9c3c48bcae7b.png)

**Comment by agilepro** [comment]
this is fixed
