### ISSUE TITLE
can't add participants

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#575]
I am in the Provisional World Children's Parliament meeting. I can't add participants to record their attendance. I record a couple of names and when I get to the third name, they disappear. This is the screen after entering three names:
![image](https://user-images.githubusercontent.com/10082365/122673759-eceea480-d19f-11eb-8b1a-57cfb55c8a2b.png)

**Comment by agilepro** [comment]
meeting was refreshing.  fixed now
