### ISSUE TITLE
can log participants

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#582]
I tried this morning to log in people to the participants list. I would add a name. Then the second. When I tried to add a third name, the first two disappeared.

**Comment by agilepro** [comment]
this is a problem with the sync from server which only occurs WHILE RUNNING a meeting.  The refresh was wiping out changes if it occurred while a person was editing the participants.

addressed this by isolating the edit operation to a different variable, and then updating the entire thing when you click save.
