### ISSUE TITLE
correct the email address

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#584]
when I was trouble shooting the sign up process (see previous issue just logged), I noticed that the system still has an email for me that is no longer functional. (I think we've talked about this before.)  Is there any harm in leaving it or does it need to be changed?

![image](https://user-images.githubusercontent.com/10082365/128879098-c823c9ca-1568-4c2a-811d-fb7082e5b4ac.png)

**Comment by agilepro** [comment]
John,

Did you log in with that disfunctional email address?  This page seems to be showing the address you logged in with.   You should log in using the email that is valid.   Can you confirm?

-Keith

**Comment by agilepro** [comment]
So I checked, and this is displaying the email address that you used to log in.   You should not be using an email address that does not work to log in.  What you need to do is to log out, and then set the password for the correct email address, and log in with that.

Please let me know if you get this message.

-Keith

**Comment by agilepro** [comment]
John, please make a comment on this issue on GitHub

**Comment by agilepro** [comment]
I don't believe that communicating through GitHub list is working.  It seems that issues are left, but the is never any follow up after that.
