### ISSUE TITLE
problem with New Round form in Topics

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#585]
I set up a topic. I then clicked Create New Round.  It autofilled in all the members. I didn't want all those members in the round. I deleted some names and saved as draft.  All the names appeared in the Round form - none were eliminated. I was only able to delete names from the form - but was still left with a strange entry at the bottom with (??? and my name)

![image](https://user-images.githubusercontent.com/10082365/129448100-d601401a-dcec-45b9-a565-5021c63becb3.png)

**Comment by agilepro** [comment]
looks like this now

![image](https://user-images.githubusercontent.com/5544889/163892856-46f77f21-f4ee-4739-ab52-a019735f4016.png)

**Comment by agilepro** [comment]
This is what it does:   for every subscriber of the topic, it creates a spot for a response.

Why would you have subscribers, when you don't want responses from them?

Deleting the rows functions.

There is a note that deleting names from the popup dialog will NOT delete the rows.

No further changes needed.
