### ISSUE TITLE
Is there something wrong with email?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#587]
I went to send an announcement of our special meeting with Angelika. This is what I saw - an apparent backlog of messages waiting to be sent:

![image](https://user-images.githubusercontent.com/10082365/130552232-78cbb2b3-f090-48a4-a820-f3a13c6b4172.png)

**Comment by agilepro** [comment]
Yes, unfortunately, that is a reliable indicator.   Will restart it in ~30 minutes.

————
Keith D Swenson
