### ISSUE TITLE
Not 4

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#589]
Everyone is getting this message when they try to log into Weaver. If you click Advanced, you can get in but it says there is no security certificate

![image](https://user-images.githubusercontent.com/10082365/132986757-d6c33e3c-c43f-4b58-ab32-c0fb20c380a8.png)

**Comment by stormcl** [comment]
I've experienced the same, and the link i sent to get people to help schedule works for me, but everyone else gets an error message that they cannot get around, that the site is mimicking Weaver but isn't? I emailed you a screenshot.

**Comment by agilepro** [comment]
this is fixed now, however it took a while . . .
