### ISSUE TITLE
24 vs 12 hour time confusion

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#59]
See HPA top circle meeting. The Meeting time says it starts 15:30 (ie 24 hour time) but the items themselves say 03:30 (12 hour time). Recommend all times be 24 hour time so we dont have to have am or pm.  Most important thing is to be consistent.

**Comment by agilepro** [comment]
OK, I searched and every date conversion I could find was set to user 24 hour mode.  I am sure at least this is consistent around the times in the meeting.
