### ISSUE TITLE
Make a way to enter expected situation for attending meetings.

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#591]
On the attendee screen, how do I make an entry into the situation column and the expected column? I have no problem entering info into the Attended Column  
UPDATE: an "oh duh" moment. I just went back to that screen and saw that a message to me was displaying asking about my attendance. I hadn't seen it because I knew I couild click on the attended column. That made me try to click on my name and when that didn't work then on the "unknown" in the expected column. Just a UI thing.

![image](https://user-images.githubusercontent.com/10082365/137240381-7a689c5a-612b-4fe1-a594-04ac64a01faa.png)

**Comment by agilepro** [comment]
this is fixed now.  Double click and enter the values.  Also a lot of other subtle things resolved.
