### ISSUE TITLE
cant find context of two Need to Respond items

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#596]
My clean up campaign continues - and related questions: 
These two remaining items in my Need to Respond box are puzzling. If I click on the target icon, I'm just taken to a meeting and I can't see the context of the comments. 

![image](https://user-images.githubusercontent.com/10082365/148310139-fcb166c7-f1ed-4500-b635-3d60cdf3a5c3.png)

**Comment by agilepro** [comment]
You have to look through all the agenda items.  Unfortunately, there is no way to directly address the agenda items.  That was the whole reason that I made comment display page.
