### ISSUE TITLE
need an email or not message for topic closures

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#597]
Copied you on an email message to Jane Baxter. Text:

Thanks for your message! It's much needed feedback. Background: I am part of a team that is continuing to develop the Circle Weaver app (software to support meetings) - we used an early version of it when we did the Advanced Facilitation class online some time ago. I've been trying to do some clean-up as we move Circle Weaver toward full availability. I closed some open topics because I didn't want to delete the class records. Your feedback alerts me to a hole in the software - viz, that when one closes an open topic there needs to be a choice of whether to send an email about the closure or not. I've copied Keith Swenson, our lead programer, on this message so that he gets the feedback, too.
Anyway, to address your question. You can certainly open the messages if you're curious about them, but otherwise just delete them. If you want to review the record of the whole the class, you can go to: https://s06.circleweaver.com/weaver/t/socio/advanced-facilitation-class-fa/RoleManagement.htm.

**Comment by agilepro** [comment]
I believe I did this several weeks ago, didn't I?

**Comment by agilepro** [comment]
no reply.  closed
