### ISSUE TITLE
a tweak

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#599]
It would be convenient if the action item dropdown box had another option in addition to Completed.  Eg, it would be helpful to have a "Skipped" option. Now, the only way to mark an item "Skipped" takes about 6 clicks

![image](https://user-images.githubusercontent.com/10082365/148695544-44d0e371-28ff-447f-a877-0eb89f971388.png)

**Comment by agilepro** [comment]
I think we should carefully consider how it is that a lot of actions items get created and then skipped.  What can we learn from that?

**Comment by agilepro** [comment]
done
