### ISSUE TITLE
see email

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#601]
Please see email I forwarded you from Bill Fleming. More connection and email problems.

**Comment by agilepro** [comment]
John,

The string "Bill Fleming" is not an email address.  For some reason he has entered his name in the space where his email address is supposed to go.  You can see this in the error message and screen shot below.  The browser will continue to fill in the value after you do it once, so you have to manually enter the email address.

That would explain why he is not receiving email.  In the log file I see that he did get sent a password reset email, however there is no evidence that he got logged in after that.

The anonymous Reply page had the error he said, fixed. Yes, he should have been able to access that without being logged in.   It should work now.

I don't know who "kewson.com" is either, my domain is "kswenson.com"

I looked for evidence of role request, but didn't find any.  I might have been looking at the wrong project.

-Keith
