### ISSUE TITLE
flaky rounds

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#604]
When you prepare a round and post without email, it sends an email anyway
![image](https://user-images.githubusercontent.com/10082365/151275392-d3b680b7-a9fc-4afe-b401-ac219297815d.png)

If you delete a round, it automatically sends an email without even telling you - and with no choice on your part - and it isn't logged in the Sent email record.

**Comment by agilepro** [comment]
Excellent.

Yes, I found that the logic was confused between SEND and RESEND.   Now:

- Post No Email will not send
- Close No Email will not send
- others will send

Should be all better
