### ISSUE TITLE
search function is flawed

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#605]
I did a search for Provisional World Children's Parliament but got this result.

![image](https://user-images.githubusercontent.com/10082365/151572783-bb508999-cc2e-44bd-bca9-09550ad49626.png)

I first searched under pwcp. Even though I changed by search words - the message in the green field kept saying "pwcp"

I then tried searching on Board. It shifted over the search term but still gave no results

![image](https://user-images.githubusercontent.com/10082365/151573374-ae30246c-f23f-4bd9-b310-f04856293fc5.png)

However, i could find it under watched workspaces

**Comment by agilepro** [comment]
no problem

![image](https://user-images.githubusercontent.com/5544889/151598950-c72bfdaa-4bd2-416f-83be-1ed627276a46.png)

I believe the issues is the the one I reported: right now the index did not get initialized globally, but as soon as you touch the project it gets indexed correctly.  Now it have been touched, now the search results are fine.
