### ISSUE TITLE
Inconsistent "skipped" button

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#607]
Skipping an action item from the dropdown box in the Action Item list makes the item disappear. But if I do it from within the action item box, it still stays on the list of action items. 

For example, this "Skipped" symbol appeared after I changed the status by opening the item and changing the status.
![image](https://user-images.githubusercontent.com/10082365/152185163-2bb26950-64c9-4dbc-934c-5d5130937993.png)

However, if I just select the symbol from the pulldown box, 
![image](https://user-images.githubusercontent.com/10082365/152185449-ce2703df-5128-4264-9f82-644921e093d2.png)

it disappears
![image](https://user-images.githubusercontent.com/10082365/152185606-ccfed9b1-77d6-4e76-8fda-a2eaab060c6a.png)

**Comment by agilepro** [comment]
using the pull down no longer makes it disappear
