### ISSUE TITLE
agenda not updating

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#608]
I cloned a new meeting and worked up a new agenda. I want to send the agenda to someone for their review but the name of the new agenda is not in the title. The old title is still showing.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/10082365/154597911-0fdb1de6-d658-465a-a164-c16396f602a7.png">

**Comment by agilepro** [comment]
This is fixed.   Refresh the page would have taken care of it.  Or navigating to the page.
