### ISSUE TITLE
wrong date shows up

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#611]
When I open the link to the agenda for the March 20 meeting of the PWCP for 20 March, the date of 13 March also shows up in small letters below the main March 20 date. I can't figure out how it gets there.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/10082365/158959895-51548bd2-6474-49ee-abbd-c52e479fd3f3.png">

**Comment by agilepro** [comment]
sent email, no confirmation, closing as USER ERROR
