### ISSUE TITLE
bug in the scheduler

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#612]
Tried to use the Weaver scheduler for a meeting with Cynthia, Keith, John. 
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/10082365/163424919-3ea38602-1163-4ad8-8477-42792bde7a08.png">

Clicked on Matt and Swarnalakshmi to remove them
<img width="214" alt="image" src="https://user-images.githubusercontent.com/10082365/163425038-8691e955-89dc-439a-b84a-8811ca54a811.png">

But when I clicked Remove User. Nothing happened. (Note: if I clicked on Go to Profile, that worked.

**Comment by agilepro** [comment]
Actually I fixed all of those occurrences yesterday, by coincidence.   Lots of fixes under the covers, like sometimes the images would not be displayed correctly.  Should be all fixed next time I upload the server.

You will NOT see the remove user any more in this location.   All other locations with icons will have the "go to profile"
