### ISSUE TITLE
can't create a child workspace

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#616]
I am trying to create a child workspace under GovernanceAlive workspace. I am administrator of that workspace. However, I'm getting a message 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/10082365/184679840-64bcfc30-700c-4cb1-a8aa-f876a7785400.png">

Why can't I create a child workspace as a workspace administrator? Does that mean only one person in a site can ever create a workspace? Doesn't seem practical if you have lots of workspaces in a site.  (Also, I think I've been able to create workspaces in the past because there are already several children under GovernanceAlive workspace

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/10082365/184680272-79ebbdfa-befd-4dc9-acc2-4585305937dc.png">

**Comment by agilepro** [comment]
User should read the error message.
