### ISSUE TITLE
small bug with Round boxes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#618]
For our meeting today, was in Draft mode and created a new agenda item (about email). I opened up a Round box. When I then went into Planning Mode, the box had disappeared. I entered it again - and now it seems fine.  

Request: retain boxes created in Draft mode.

More data:  I just noticed that the Round box was showing up in the next agenda Item "Design" - I diont know if I inadvertently created it there or it it hopped from the draft item to the next agenda item. (I have now removed the box from the Design item)

**Comment by agilepro** [comment]
Be great if you can reproduce this problem.
