### ISSUE TITLE
strange error message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#619]
when I enter the word keystone into the search field, I get this error message. (we have a circle called the Keystone Circle)

<img width="580" alt="image" src="https://user-images.githubusercontent.com/10082365/188290670-59cf9293-d4e6-4d0f-afff-6c3574de5fed.png">

**Comment by agilepro** [comment]
Can't reproduce.  Not enough information here.  It is a shame.  What i need is a complete description of how to make the problem happen, including where you were at the time.   

I did find a workspace named "keynote" and I have to assume this is a user error
