### ISSUE TITLE
creating aciton items

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#620]
After the meeting this evening, I tried twice to create an action item telling Cynthia and me to read keith's proposed blog posts I categorized in the outreach category. I clicked Save. Both times the action item did not appear in the action items list.

**Comment by agilepro** [comment]
I need a reproducible set of steps to demonstrate the problem.  You did not even mention which of the 5 or so ways to create an action item you are referring to.  I need the specific context, and then the specific buttons or menu options you used.  Without that, reporting bug is pointless.

The vague description "creating actions items does not work" is too vague.  I guarantee you that creating action items works, or else there would not be any action items.
