### ISSUE TITLE
Create Decision stores current date, not date specified in Details tab

### ISSUE THREAD

**Issue by leilatite** [agilepro/cognoscenti#621]
When I create a new decision for decisions made in the past, it always stores them with whatever is the current date. If I've specified a particular date on the Details tab, I would expect the system to store the decision with that date. If I edit the decision and put in the date again, then it saves the correct date.

**Comment by agilepro** [comment]
Seems like a reasonable request.

**Comment by agilepro** [comment]
**OK, thanks for reporting this!**

I found a specific line that was overriding the specified time, with the current time, when the decision was new.    I don't really see any reason for this so I am removing it.

The fix will be in the next installation of the server.
