### ISSUE TITLE
can't edit roles

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#628]
Created a workspace called UI test, but the system won't let me modify the readonly status of the many roles.  For example, there are times when a facilitator needs to be an editor but that role is pre-set as read only - and no ability to change it. 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/10082365/213947123-1a4236f0-b097-4d09-a277-f3dc64623874.png">

**Comment by agilepro** [comment]
Administrator and Members can not change their edit status.  Those two roles are special.

You didn't mention the actual role that you tried to modify, so I can only assume that you tried to modify either members or administrators.
