### ISSUE TITLE
why -1 bytes?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#638]
On the copy or move document page, why do many of the files show a size of -1 bytes?

<img width="499" alt="image" src="https://user-images.githubusercontent.com/10082365/232262101-b42b0585-d409-440c-b243-fe51c283b2b9.png">

**Comment by agilepro** [comment]
It means it is a URL and has no actual document on disk

updated to this:

![image](https://user-images.githubusercontent.com/5544889/235450779-a898e377-5008-475c-b46d-1ccba4fa9370.png)
