### ISSUE TITLE
A few consented proposals have no decisions

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#7]
If you go to John's topic: Decisions Made to This Point in Time (4 Dec 2015) https://interstagebpm.com/av/t/socio/weaver-design-team/noteZoom0572.htm
you will not a few fully consented proposals that have no links to decisions.

Again a problem (bug) with the workflow design.  There is no process in place to prevent proposals from falling into a limbo state without conclusion.

**Comment by iangilman** [comment]
Are the action items for this different than for #6?

**Comment by agilepro** [comment]
There is a list to show all UNCLOSED rounds.  When you close, you decide to make a decision or not.  That should do it.
