### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#76]
Need a way to generate decisions from the Create Minutes button. Right now if you generate a decision from the Create Proposal button, you can in the drop down box select "Generate Decision" and presto you get a decision in the decision list. There is no way to do that from the Create Minutes button. It is confusing that you can generate minutes either from Create Proposal and from Create Minutes. One solution would be to eliminate Generate Proposal from the sync meeting format and be able to a decision from Create Minutes by highlighting text.

**Comment by agilepro** [comment]
I removed the restriction that decisions could only be made from proposals.   Now, you can make a decisions from any kind:  comment, proposal, round, or minutes.  In each case it copies the text in, and allows you to edit it.
