### ISSUE TITLE
URLs should be decomposable

### ISSUE THREAD

**Issue by iangilman** [agilepro/cognoscenti#78]
I'm on the topics page for a circle:

https://interstagebpm.com/av/t/socio/weaver-design-team/notesList.htm

… and I want to go to that circle's front page. I should be able to just shave off the last directory in the URL, like so:

https://interstagebpm.com/av/t/socio/weaver-design-team/

… but unfortunately that URL gives an error instead.

Likewise, if I wanted to go further up the chain to the site, I should be able to shave off another directory like so:

https://interstagebpm.com/av/t/socio/

… but again that page gives an error as well.

**Comment by iangilman** [comment]
Note that ideally the front page for the circle should just be the unadorned:

https://interstagebpm.com/av/t/socio/weaver-design-team/

… rather than what it is now:

https://interstagebpm.com/av/t/socio/weaver-design-team/frontPage.htm

… but even if that can't be fixed, at least the unadorned directory can forward to the correct page.

**Comment by agilepro** [comment]
I see this.  I agree, however I wonder how many actual users do this (I do, and you clearly do, but are not normal).

It is easy enough to make the shaved off URL redirect to the proper one.  sort of like "index.html" functionality.  That would allow you to shave the URL and get to a meaningful place and not an error.
