### ISSUE TITLE
forced link between topic cited and agenda item title

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#86]
In preparing the minutes for July 29 I added minutes of the previous meeting to the topic. However, that forced the title of the topic to change from Admin Matters to the full title of the previous meeting. I could not override this new topic title. Need to be able to override the automatic titling of an agenda topic. The topic cited may not reflect the whole scope of the intended topic title.

**Comment by agilepro** [comment]
now there are automatically generated links to the previous topics
