### ISSUE TITLE
identity for Recent Updates items

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#88]
Problem: I find that when I look at the Recent Updates box, I am
1) happy to see a complete list
2) confused about which are action items (are they mine or someone else's?), which are topics, etc. Without this information, I don't know whether to look at the item or not

Request: indicate whether items in Recent Updates are action items (and whose), new topics, topic updates, "other".

**Comment by johnabuck** [comment]
in the Park Office Training workspace, I just gave Carol a new role. It shows up fine in the Role tab but is not showing on the Front Page tab. Is there a delay? How long? Can the delay be reduced?

**Comment by agilepro** [comment]
Your action items are listed in a box labeled "Your Action Items".  

There is a page called "Activity Steam" which shows a lot of detail about what the items are, who changed them, and maybe even why.  Maybe the best idea is to put a search icon on this panel title to take you to the Activity Stream page.

**Comment by agilepro** [comment]
added search buttons for these on the front page
