### ISSUE TITLE
No facilitator role option baked into process workflow

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#9]
Right now there's no option for a member to jump in to facilitate the workflow taking a seed proposal idea through to a decision resolution.  We've all agreed we want this.

Now we need to design it into the overall workflow process and supporting software.

I've suggested anyone can jump into the role at anytime for any proposal to decision workflow, but that there be clear rules and timers imposed on every possible step a facilitator can make too, so again it is always clear when a workflow is in a limbo state.  Limbo state workflows are very important to track and report and alert on.  Also a great way to measure member and circle performance via.

**Comment by iangilman** [comment]
It's unclear to me what the action item is here...maybe this should be a Topic in Weaver instead? 

I think for starters this is more of a process question than a design question. I recall @johnabuck saying that he would take on the facilitator role in our async conversations...I'm not sure that's happened yet?

**Comment by agilepro** [comment]
I agree.  Design issues should be discussed in the Weaver "Discussion Topic" space.   There, we are attempting to identify the features and capabilities that we want to see, and they are not well defined.  HERE (in the issues list) I just want bug reports of clear coding problems.  That is: there is a clear feature in the product, but it does not work in some situation, and the issue should include details about the situation that it does not work properly in.

**Comment by agilepro** [comment]
ALSO one comment elsewhere (a different issue) says that it si a bad idea that currently anyone can jump in and take a proposal to a decision.  This issue seems to say that it is a good idea for anyone to jump in and take a proposal to a decision.  I am confused about what the workflow you have in mind, and who should be allowed to do it.  To clarify this, explain exactly (including all steps) what the workflow is, and what restrictions should be placed on who can do what step.

**Comment by agilepro** [comment]
Some of the things have been addressed.  We have email reminders on notes.  We have due dates, and you can set/change the due dates.  It is not clear how to "jump in" and it is not clear what workflow we are talking about.  Closing this due to it being unclear what action to take on this.
