### ISSUE TITLE
404 error when trying to Update Email Address

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#90]
I am trying to add an email address for Derryl. When I select Update Settings, I get a 404 error.

![image](https://cloud.githubusercontent.com/assets/10082365/17253166/8b76bc40-557d-11e6-8ba0-61dae389db9e.png)

**Comment by agilepro** [comment]
What option did you use to ADD an email address?

**Comment by agilepro** [comment]
There is no option to update email.  Not sure what course of action led to this, but I can't find any option in the system that fits the description.
