### ISSUE TITLE
meaning of workspaces

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#92]
In demoing Weaver to some new users, we found the word Workspaces at the top upper left next to the logo juxtaposed with the word Workspace on the left of the next line below is confusing. I gave one person access to Weaver Sandbox as well as two organizations. At first it seemed as if he had to log in and out of each workspace to move between them. He stumbled on the fact that Workspaces lets him do that but Workspace does not. Maybe Workspaces could be called Your Workspaces and the tab Sites could not appear at all unless someone had access to more than one site..

**Comment by agilepro** [comment]
That is good feedback from a user.

The purpose of the "Workspace" in the breadcrumbs is to tell you context for the name that follows it in the breadcrumbs.  It can either be "Workspace", "Site", or "Users".    It is not clear how important this is.  Theoretically there could be a site that has the same name as a user, but how often does that happen, and even there are other clues about whether you are looking at a site or a user page.  

Maybe we should just eliminate that word from the beginning of the bread crumbs?

**Comment by iangilman** [comment]
Briana also found it confusing… Let's try removing it.

**Comment by agilepro** [comment]
I have pulled that out.  We can try it that way, see how it works.
