### ISSUE TITLE
presenter

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#97]
in setting up an synch meeting agenda item, the Presenter function doesn't work. I go into settings, enter a persons name as presenter, save, and then nothing shows up

**Comment by agilepro** [comment]
This is another case of "assigning people to things" usability.  You have to select the person from the list, then click ADD (right next to their name) and then click SAVE.  If you do that, it works.  If you don't click ADD then it does not get added, and the Save does not save anything.

I believe this adding people to lists is one of the biggest usability problems.

**Comment by agilepro** [comment]
I fixed this by putting the new assign people code into that place
